# -*- coding: utf-8 -*-
import json
import os
import random

random.seed(42)

def build_part3_files():
    print("Building Part 3 Question Database (GK08501 - GK10000)...")
    
    # -------------------------------------------------------------
    # 1. STATIC GK (250 questions: GK08501 to GK08750)
    # -------------------------------------------------------------
    static_facts = [
        # Organizations & Headquarters
        ("Where is the headquarters of the International Atomic Energy Agency (IAEA) located?", "अंतर्राष्ट्रीय परमाणु ऊर्जा एजेंसी (IAEA) का मुख्यालय कहाँ स्थित है?", ["Vienna, Austria", "Geneva, Switzerland", "New York, USA", "Paris, France"], ["विएना, ऑस्ट्रिया", "जिनेवा, स्विट्जरलैंड", "न्यूयॉर्क, अमेरिका", "पेरिस, फ्रांस"], 0, "IAEA headquarters is located in Vienna, Austria, established in 1957.", "अंतर्राष्ट्रीय परमाणु ऊर्जा एजेंसी का मुख्यालय विएना (ऑस्ट्रिया) में है।", "Easy", "Important Organizations & Headquarters"),
        ("Where is the headquarters of the International Court of Justice (ICJ) located?", "अंतर्राष्ट्रीय न्यायालय (ICJ) का मुख्यालय कहाँ स्थित है?", ["The Hague, Netherlands", "Geneva, Switzerland", "London, UK", "Rome, Italy"], ["द हेग, नीदरलैंड्स", "जिनेवा, स्विट्जरलैंड", "लंदन, ब्रिटेन", "रोम, इटली"], 0, "The Peace Palace in The Hague, Netherlands hosts the ICJ, the principal judicial organ of the UN.", "अंतर्राष्ट्रीय न्यायालय का मुख्यालय द हेग (नीदरलैंड्स) के पीस पैलेस में स्थित है।", "Easy", "Important Organizations & Headquarters"),
        ("Where is the headquarters of the World Trade Organization (WTO) located?", "विश्व व्यापार संगठन (WTO) का मुख्यालय कहाँ स्थित है?", ["Geneva, Switzerland", "Washington D.C., USA", "Paris, France", "Brussels, Belgium"], ["जिनेवा, स्विट्जरलैंड", "वाशिंगटन डी.सी., अमेरिका", "पेरिस, फ्रांस", "ब्रुसेल्स, बेल्जियम"], 0, "WTO was established on 1 January 1995 with headquarters in Geneva, Switzerland.", "विश्व व्यापार संगठन (WTO) की स्थापना 1995 में हुई और इसका मुख्यालय जिनेवा में है।", "Easy", "Important Organizations & Headquarters"),
        ("Where is the headquarters of the International Maritime Organization (IMO) situated?", "अंतर्राष्ट्रीय समुद्री संगठन (IMO) का मुख्यालय कहाँ स्थित है?", ["London, United Kingdom", "Geneva, Switzerland", "Monaco", "Athens, Greece"], ["लंदन, यूनाइटेड किंगडम", "जिनेवा, स्विट्जरलैंड", "मोनाको", "एथेंस, ग्रीस"], 0, "IMO is the specialized agency of the UN responsible for maritime safety with headquarters in London.", "अंतर्राष्ट्रीय समुद्री संगठन (IMO) का मुख्यालय लंदन (यूके) में स्थित है।", "Moderate", "Important Organizations & Headquarters"),
        ("Where is the headquarters of the Food and Agriculture Organization (FAO) located?", "खाद्य एवं कृषि संगठन (FAO) का मुख्यालय कहाँ स्थित है?", ["Rome, Italy", "Paris, France", "Bern, Switzerland", "Madrid, Spain"], ["रोम, इटली", "पेरिस, फ्रांस", "बर्न, स्विट्जरलैंड", "मैड्रिड, स्पेन"], 0, "FAO was established in 1945 and its headquarters is located in Rome, Italy.", "खाद्य एवं कृषि संगठन (FAO) का मुख्यालय रोम (इटली) में स्थित है।", "Easy", "Important Organizations & Headquarters"),
        ("Where is the headquarters of the Universal Postal Union (UPU) located?", "सार्वभौमिक डाक संघ (UPU) का मुख्यालय कहाँ स्थित है?", ["Bern, Switzerland", "Zurich, Switzerland", "Vienna, Austria", "Brussels, Belgium"], ["बर्न, स्विट्जरलैंड", "ज्यूरिख, स्विट्जरलैंड", "विएना, ऑस्ट्रिया", "ब्रुसेल्स, बेल्जियम"], 0, "UPU was established by the Treaty of Bern in 1874, with its headquarters in Bern, Switzerland.", "सार्वभौमिक डाक संघ (UPU) का मुख्यालय बर्न (स्विट्जरलैंड) में है।", "Moderate", "Important Organizations & Headquarters"),
        ("Where is the Central Rice Research Institute (CRRI) located in India?", "भारत में केंद्रीय चावल अनुसंधान संस्थान (CRRI) कहाँ स्थित है?", ["Cuttack, Odisha", "Karnal, Haryana", "Shimla, HP", "Coimbatore, TN"], ["कटक, ओडिशा", "करनाल, हरियाणा", "शिमला, हिमाचल प्रदेश", "कोयंबटूर, तमिलनाडु"], 0, "ICAR-National Rice Research Institute is located at Cuttack, Odisha.", "केंद्रीय चावल अनुसंधान संस्थान कटक (ओडिशा) में स्थित है।", "Easy", "Important Organizations & Headquarters"),
        ("Where is the Central Potato Research Institute (CPRI) situated in India?", "केंद्रीय आलू अनुसंधान संस्थान (CPRI) कहाँ स्थित है?", ["Shimla, Himachal Pradesh", "Dehradun, Uttarakhand", "Kufri / Shimla", "Ranchi, Jharkhand"], ["शिमला, हिमाचल प्रदेश", "देहरादून, उत्तराखंड", "कुफरी / शिमला", "राँची, झारखंड"], 0, "Central Potato Research Institute is located at Shimla (Himachal Pradesh).", "केंद्रीय आलू अनुसंधान संस्थान शिमला (हिमाचल प्रदेश) में स्थित है।", "Easy", "Important Organizations & Headquarters"),
        ("Where is the National Dairy Research Institute (NDRI) located in India?", "राष्ट्रीय डेयरी अनुसंधान संस्थान (NDRI) कहाँ स्थित है?", ["Karnal, Haryana", "Anand, Gujarat", "Ludhiana, Punjab", "Mathura, UP"], ["करनाल, हरियाणा", "आणंद, गुजरात", "लुधियाना, पंजाब", "मथुरा, उत्तर प्रदेश"], 0, "NDRI is India's premier dairy research institute located in Karnal, Haryana.", "राष्ट्रीय डेयरी अनुसंधान संस्थान (NDRI) करनाल (हरियाणा) में स्थित है।", "Easy", "Important Organizations & Headquarters"),
        ("Where is the Forest Research Institute (FRI) located in India?", "केंद्रीय वन अनुसंधान संस्थान (FRI) कहाँ स्थित है?", ["Dehradun, Uttarakhand", "Jabalpur, MP", "Shillong, Meghalaya", "Bhopal, MP"], ["देहरादून, उत्तराखंड", "जबलपुर, मध्य प्रदेश", "शिलांग, मेघालय", "भोपाल, मध्य प्रदेश"], 0, "Forest Research Institute of India is located at Dehradun, Uttarakhand, established in 1906.", "भारतीय वन अनुसंधान संस्थान देहरादून (उत्तराखंड) में स्थित है।", "Easy", "Important Organizations & Headquarters"),
        
        # Awards & Honors
        ("Which is the highest civilian award of the Republic of India?", "भारत गणराज्य का सर्वोच्च नागरिक सम्मान कौन सा है?", ["Bharat Ratna", "Padma Vibhushan", "Padma Bhushan", "Param Vir Chakra"], ["भारत रत्न", "पद्म विभूषण", "पद्म भूषण", "परमवीर चक्र"], 0, "Bharat Ratna, instituted in 1954, is India's highest civilian honour.", "भारत रत्न (1954 में स्थापित) भारत का सर्वोच्च नागरिक पुरस्कार है।", "Easy", "Important Awards & Honors"),
        ("Which is India's highest military decoration awarded for valor in wartime?", "युद्ध काल में वीरता के लिए दिया जाने वाला भारत का सर्वोच्च सैन्य पदक कौन सा है?", ["Param Vir Chakra (PVC)", "Maha Vir Chakra", "Vir Chakra", "Ashoka Chakra"], ["परमवीर चक्र (PVC)", "महावीर चक्र", "वीर चक्र", "अशोक चक्र"], 0, "Param Vir Chakra is India's highest wartime gallantry medal, first awarded to Major Somnath Sharma.", "परमवीर चक्र भारत का सर्वोच्च युद्धकालीन वीरता पदक है, जो सर्वप्रथम मेजर सोमनाथ शर्मा को मिला था।", "Easy", "Important Awards & Honors"),
        ("Which is India's highest peacetime gallantry award?", "शांति काल में दिया जाने वाला भारत का सर्वोच्च वीरता पुरस्कार कौन सा है?", ["Ashoka Chakra", "Kirti Chakra", "Shaurya Chakra", "Sena Medal"], ["अशोक चक्र", "कीर्ति चक्र", "शौर्य चक्र", "सेना मेडल"], 0, "Ashoka Chakra is the peacetime equivalent of the Param Vir Chakra.", "अशोक चक्र शांतिकालीन वीरता का सर्वोच्च भारतीय सैन्य सम्मान है।", "Easy", "Important Awards & Honors"),
        ("The prestigious 'Dadasaheb Phalke Award' is given in which field?", "प्रतिष्ठित 'दादा साहब फाल्के पुरस्कार' किस क्षेत्र में दिया जाता है?", ["Indian Cinema", "Literature", "Classical Music", "Journalism"], ["भारतीय सिनेमा", "साहित्य", "शास्त्रीय संगीत", "पत्रकारिता"], 0, "Dadasaheb Phalke Award is India's highest award in cinema, first awarded to Devika Rani in 1969.", "दादा साहब फाल्के पुरस्कार भारतीय सिनेमा का सर्वोच्च सम्मान है (प्रथम प्राप्तकर्ता: देविका रानी, 1969)।", "Easy", "Important Awards & Honors"),
        ("The 'Jnanpith Award' is India's highest literary honour. Who was its first recipient?", "ज्ञानपीठ पुरस्कार भारत का सर्वोच्च साहित्य सम्मान है। इसके प्रथम प्राप्तकर्ता कौन थे?", ["G. Sankara Kurup (Malayalam)", "Rabindranath Tagore", "Sumitranandan Pant", "Ramdhari Singh Dinkar"], ["जी. शंकर कुरुप (मलयालम)", "रवींद्रनाथ टैगोर", "सुमित्रानंदन पंत", "रामधारी सिंह दिनकर"], 0, "Malayalam poet G. Sankara Kurup won the first Jnanpith Award in 1965 for 'Odakkuzhal'.", "मलयालम कवि जी. शंकर कुरुप को 1965 में प्रथम ज्ञानपीठ पुरस्कार प्रदान किया गया था।", "Moderate", "Important Awards & Honors"),
        ("The 'Abel Prize' is an international prize awarded annually in which field?", "अंतर्राष्ट्रीय 'एबेल पुरस्कार' (Abel Prize) प्रतिवर्ष किस क्षेत्र में दिया जाता है?", ["Mathematics", "Architecture", "Medicine", "Theoretical Physics"], ["गणित (Mathematics)", "वास्तुकला", "चिकित्सा", "सैद्धांतिक भौतिकी"], 0, "The Abel Prize, awarded by the King of Norway, is considered the Nobel of Mathematics.", "एबेल पुरस्कार को गणित का नोबेल पुरस्कार माना जाता है, जो नॉर्वे की सरकार द्वारा दिया जाता है।", "Moderate", "Important Awards & Honors"),
        ("The 'Pritzker Architecture Prize' is globally recognized as the highest honor in:", "प्रित्जकर पुरस्कार (Pritzker Prize) विश्व स्तर पर किस क्षेत्र का सर्वोच्च सम्मान है?", ["Architecture", "Music", "Journalism", "Environment"], ["वास्तुकला (Architecture)", "संगीत", "पत्रकारिता", "पर्यावरण"], 0, "The Pritzker Prize is regarded as architecture's Nobel Prize (B.V. Doshi was the first Indian winner).", "प्रित्जकर पुरस्कार वास्तुकला का सर्वोच्च वैश्विक सम्मान है (बालकृष्ण दोशी प्रथम भारतीय विजेता थे)।", "Moderate", "Important Awards & Honors"),
        ("The 'Pulitzer Prize' is administered by Columbia University for excellence in:", "पुलित्जर पुरस्कार किस क्षेत्र में विशिष्ट योगदान के लिए दिया जाता है?", ["Newspaper Journalism, Literature & Music", "Cinema & Acting", "Peace & Diplomacy", "Economics"], ["समाचार पत्रकारिता, साहित्य एवं संगीत", "सिनेमा एवं अभिनय", "शांति एवं कूटनीति", "अर्थशास्त्र"], 0, "Pulitzer Prizes are awarded annually across journalism, books, drama, and music.", "पुलित्जर पुरस्कार पत्रकारिता, साहित्य और संगीत रचना के लिए प्रदान किया जाता है।", "Easy", "Important Awards & Honors"),
        ("Who was the first Indian to win the Nobel Prize in Physics in 1930?", "1930 में भौतिकी का नोबेल पुरस्कार जीतने वाले प्रथम भारतीय वैज्ञानिक कौन थे?", ["Sir C. V. Raman", "Homi J. Bhabha", "Subrahmanyan Chandrasekhar", "Satyendra Nath Bose"], ["सर सी. वी. रमन", "होमी जहांगीर भाभा", "सुब्रह्मण्यन चंद्रशेखर", "सत्येंद्र नाथ बोस"], 0, "Sir C.V. Raman won the Nobel Prize in Physics in 1930 for the discovery of Raman Scattering.", "सर सी.वी. रमन को रमन प्रभाव की खोज के लिए 1930 में भौतिकी का नोबेल पुरस्कार मिला था।", "Easy", "Important Awards & Honors"),
        ("Who was the first Indian citizen to be awarded the Ramon Magsaysay Award in 1958?", "1958 में रेमन मैग्सेसे पुरस्कार पाने वाले प्रथम भारतीय कौन थे?", ["Acharya Vinoba Bhave", "Jayaprakash Narayan", "Mother Teresa", "Dr. Verghese Kurien"], ["आचार्य विनोबा भावे", "जयप्रकाश नारायण", "मदर टेरेसा", "डॉ. वर्गीज कुरियन"], 0, "Acharya Vinoba Bhave won the inaugural Ramon Magsaysay Award for Community Leadership in 1958.", "आचार्य विनोबा भावे को भूदान आंदोलन और सामुदायिक नेतृत्व के लिए 1958 में प्रथम रेमन मैग्सेसे मिला।", "Moderate", "Important Awards & Honors"),

        # Superlatives & Landmarks
        ("Which is the largest freshwater lake in the world by surface area?", "सतह के क्षेत्रफल की दृष्टि से विश्व की सबसे बड़ी मीठे पानी की झील कौन सी है?", ["Lake Superior (North America)", "Lake Baikal (Russia)", "Lake Victoria (Africa)", "Lake Michigan"], ["सुपीरियर झील (उत्तरी अमेरिका)", "बैकाल झील (रूस)", "विक्टोरिया झील (अफ्रीका)", "मिशिगन झील"], 0, "Lake Superior is the world's largest freshwater lake by surface area (82,103 km²).", "सुपीरियर झील (उत्तरी अमेरिका) क्षेत्रफल की दृष्टि से विश्व की सबसे बड़ी मीठे पानी की झील है।", "Easy", "World & Indian Superlatives"),
        ("Which is the deepest freshwater lake in the world?", "विश्व की सबसे गहरी मीठे पानी की झील कौन सी है?", ["Lake Baikal (Russia)", "Lake Tanganyika (Africa)", "Caspian Sea", "Lake Superior"], ["बैकाल झील (रूस)", "तांगानिका झील", "कैस्पियन सागर", "सुपीरियर झील"], 0, "Lake Baikal in Siberia, Russia is the deepest lake in the world (~1,642 meters deep).", "रूस के साइबेरिया में स्थित बैकाल झील विश्व की सबसे गहरी (1,642 मीटर) और प्राचीन झील है।", "Easy", "World & Indian Superlatives"),
        ("Which is the highest waterfall in the world?", "विश्व का सबसे ऊँचा जलप्रपात कौन सा है?", ["Angel Falls (Venezuela)", "Niagara Falls", "Victoria Falls", "Iguazu Falls"], ["एंजेल जलप्रपात (वेनेजुएला)", "नियाग्रा जलप्रपात", "विक्टोरिया जलप्रपात", "इगुआजू जलप्रपात"], 0, "Angel Falls on the Churun River in Venezuela drops 979 meters (3,212 ft).", "वेनेजुएला में चुरुन नदी पर स्थित एंजेल जलप्रपात (979 मीटर) विश्व का सबसे ऊँचा जलप्रपात है।", "Easy", "World & Indian Superlatives"),
        ("Which is the largest desert in the world (including polar regions)?", "विश्व का सबसे बड़ा मरुस्थल (ध्रुवीय मरुस्थल सहित) कौन सा है?", ["Antarctic Desert", "Sahara Desert", "Arctic Desert", "Arabian Desert"], ["अंटार्कटिक मरुस्थल", "सहारा मरुस्थल", "आर्कटिक मरुस्थल", "अरब मरुस्थल"], 0, "Antarctica is technically the largest polar desert, while Sahara is the largest hot subtropical desert.", "अंटार्कटिका विश्व का सबसे बड़ा ध्रुवीय मरुस्थल है, जबकि सहारा सबसे बड़ा गर्म मरुस्थल है।", "Moderate", "World & Indian Superlatives"),
        ("Which is the longest mountain range above sea level in the world?", "विश्व की सबसे लंबी पर्वत श्रृंखला (स्थल भाग पर) कौन सी है?", ["Andes Mountains (South America)", "Himalayas (Asia)", "Rocky Mountains (North America)", "Alps (Europe)"], ["एंडीज पर्वतमाला (दक्षिण अमेरिका)", "हिमालय (एशिया)", "रॉकी पर्वतमाला", "आल्प्स (यूरोप)"], 0, "The Andes Mountains run approximately 7,000 km along western South America.", "दक्षिण अमेरिका में स्थित एंडीज पर्वतमाला (~7,000 किमी) विश्व की सबसे लंबी पर्वत श्रृंखला है।", "Easy", "World & Indian Superlatives"),
        ("Which is the highest motorable road pass in the world located in Ladakh, India?", "भारत के लद्दाख में स्थित विश्व का सबसे ऊँचा मोटर वाहन योग्य दर्रा कौन सा है?", ["Umling La Pass (19,024 ft)", "Khardung La Pass", "Zoji La Pass", "Rohtang Pass"], ["उमलिंग ला दर्रा (19,024 फीट)", "खारदुंग ला दर्रा", "ज़ोजिला दर्रा", "रोहतांग दर्रा"], 0, "Umling La pass at 19,024 ft, built by BRO in Ladakh, is the world's highest motorable road.", "सीमा सड़क संगठन (BRO) द्वारा लद्दाख में निर्मित उमलिंग ला (19,024 फीट) विश्व का सबसे ऊँचा मोटर मार्ग है।", "Moderate", "World & Indian Superlatives"),
        ("Which is the tallest statue in the world?", "विश्व की सबसे ऊँची प्रतिमा कौन सी है?", ["Statue of Unity (Gujarat, India - 182 m)", "Spring Temple Buddha (China)", "Laykyun Sekkya (Myanmar)", "Statue of Liberty (USA)"], ["स्टैच्यू ऑफ यूनिटी (गुजरात, भारत - 182 मी)", "स्प्रिंग टेम्पल बुद्ध (चीन)", "लेक्युन सेक्कया (म्यांमार)", "स्टैच्यू ऑफ लिबर्टी (अमेरिका)"], 0, "The Statue of Unity depicting Sardar Vallabhbhai Patel stands 182 meters tall in Kevadia, Gujarat.", "गुजरात के केवड़िया में स्थित सरदार वल्लभभाई पटेल की प्रतिमा 'स्टैच्यू ऑफ यूनिटी' (182 मीटर) विश्व में सबसे ऊँची है।", "Easy", "World & Indian Superlatives"),
        ("Which is the longest railway platform in the world as per Guinness World Records?", "गिनीज वर्ल्ड रिकॉर्ड्स के अनुसार विश्व का सबसे लंबा रेलवे प्लेटफॉर्म कौन सा है?", ["Shree Siddharoodha Swamiji Hubballi Station (1,507 m, Karnataka)", "Gorakhpur Railway Station (UP)", "Kollam Junction (Kerala)", "Kharagpur Railway Station (WB)"], ["श्री सिद्धारूढ़ स्वामीजी हुबली स्टेशन (1,507 मी, कर्नाटक)", "गोरखपुर रेलवे स्टेशन", "कोल्लम जंक्शन", "खड़गपुर"], 0, "Hubballi railway platform in Karnataka measures 1,507 meters in length.", "कर्नाटक का हुबली रेलवे प्लेटफॉर्म (1,507 मीटर) विश्व का सबसे लंबा रेलवे प्लेटफॉर्म है।", "Moderate", "World & Indian Superlatives"),
        ("Which is the oldest surviving classical language monument / text of India?", "भारत का प्राचीनतम जीवित शास्त्रीय ग्रंथ कौन सा है?", ["Rigveda", "Samaveda", "Yajurveda", "Atharvaveda"], ["ऋग्वेद", "सामवेद", "यजुर्वेद", "अथर्ववेद"], 0, "Rigveda is the oldest existing Sanskrit scripture dating back to c. 1500 BCE.", "ऋग्वेद विश्व का प्राचीनतम ज्ञात धार्मिक एवं साहित्यिक ग्रंथ है।", "Easy", "Static GK Landmarks & Epics"),
        ("What is the national motto of India inscribed below the State Emblem?", "भारत के राष्ट्रीय प्रतीक के नीचे उत्कीर्ण राष्ट्रीय आदर्श वाक्य क्या है?", ["Satyameva Jayate (Truth Alone Triumphs)", "Vande Mataram", "Jai Hind", "Janani Janmabhumishcha"], ["सत्यमेव जयते", "वंदे मातरम्", "जय हिंद", "जननी जन्मभूमिश्च"], 0, "The national motto 'Satyameva Jayate' is taken from the Mundaka Upanishad.", "'सत्यमेव जयते' मुंडकोपनिषद से लिया गया है और देवनागरी लिपि में उत्कीर्ण है।", "Easy", "National Symbols & Emblems"),

        # Institutions & Personalities
        ("Where is the National Defence Academy (NDA) located in India?", "राष्ट्रीय रक्षा अकादमी (NDA) भारत में कहाँ स्थित है?", ["Khadakwasla, Pune", "Dehradun", "Wellington, Nilgiris", "Dundigal, Hyderabad"], ["खड़कवासला, पुणे", "देहरादून", "वेलिंगटन, नीलगिरि", "डुंडीगल, हैदराबाद"], 0, "NDA is situated at Khadakwasla near Pune, Maharashtra.", "राष्ट्रीय रक्षा अकादमी खड़कवासला (पुणे, महाराष्ट्र) में स्थित है।", "Easy", "Important Institutions & Headquarters"),
        ("Where is the Indian Military Academy (IMA) located?", "भारतीय सैन्य अकादमी (IMA) कहाँ स्थित है?", ["Dehradun, Uttarakhand", "Mhow, MP", "Gaya, Bihar", "Chennai, TN"], ["देहरादून, उत्तराखंड", "महू, मध्य प्रदेश", "गया, बिहार", "चेन्नई, तमिलनाडु"], 0, "IMA was established in 1932 in Dehradun, Uttarakhand.", "भारतीय सैन्य अकादमी 1932 में देहरादून (उत्तराखंड) में स्थापित की गई थी।", "Easy", "Important Institutions & Headquarters"),
        ("Where is the Lal Bahadur Shastri National Academy of Administration (LBSNAA) located?", "लाल बहादुर शास्त्री राष्ट्रीय प्रशासन अकादमी (LBSNAA) कहाँ स्थित है?", ["Mussoorie, Uttarakhand", "Shimla, HP", "Nainital, Uttarakhand", "Mount Abu, Rajasthan"], ["मसूरी, उत्तराखंड", "शिमला, हिमाचल प्रदेश", "नैनीताल", "माउंट आबू"], 0, "LBSNAA trains IAS officers and civil servants in Mussoorie, Uttarakhand.", "आईएएस अधिकारियों के प्रशिक्षण संस्थान एलबीएसएनएए मसूरी (उत्तराखंड) में स्थित है।", "Easy", "Important Institutions & Headquarters"),
        ("Where is the Sardar Vallabhbhai Patel National Police Academy (SVPNPA) situated?", "सरदार वल्लभभाई पटेल राष्ट्रीय पुलिस अकादमी (SVPNPA) कहाँ स्थित है?", ["Hyderabad, Telangana", "Nagpur, Maharashtra", "New Delhi", "Bengaluru, Karnataka"], ["हैदराबाद, तेलंगाना", "नागपुर, महाराष्ट्र", "नई दिल्ली", "बेंगलुरु, कर्नाटक"], 0, "SVPNPA trains Indian Police Service (IPS) officers in Hyderabad.", "आईपीएस अधिकारियों का राष्ट्रीय प्रशिक्षण केंद्र हैदराबाद (तेलंगाना) में स्थित है।", "Easy", "Important Institutions & Headquarters"),
        ("Where is the Indira Gandhi Centre for Atomic Research (IGCAR) located?", "इंदिरा गांधी परमाणु अनुसंधान केंद्र (IGCAR) कहाँ स्थित है?", ["Kalpakkam, Tamil Nadu", "Trombay, Mumbai", "Rawatbhata, Rajasthan", "Narora, UP"], ["कलपक्कम, तमिलनाडु", "ट्रॉम्बे, मुंबई", "रावतभाटा, राजस्थान", "नरोरा, उत्तर प्रदेश"], 0, "IGCAR is located at Kalpakkam near Chennai, Tamil Nadu.", "इंदिरा गांधी परमाणु अनुसंधान केंद्र कलपक्कम (तमिलनाडु) में स्थित है।", "Moderate", "Important Institutions & Headquarters"),
        ("Where is the Satish Dhawan Space Centre (SDSC-SHAR) situated in India?", "सतीश धवन अंतरिक्ष केंद्र (SHAR) कहाँ स्थित है?", ["Sriharikota, Andhra Pradesh", "Thumba, Kerala", "Bengaluru, Karnataka", "Chandipur, Odisha"], ["श्रीहरिकोटा, आंध्र प्रदेश", "थुम्बा, केरल", "बेंगलुरु, कर्नाटक", "चांदीपुर, ओडिशा"], 0, "SDSC SHAR in Sriharikota, AP is ISRO's primary spaceport for rocket launches.", "सतीश धवन अंतरिक्ष केंद्र श्रीहरिकोटा (आंध्र प्रदेश) में स्थित भारत का मुख्य रॉकेट प्रक्षेपण केंद्र है।", "Easy", "Important Institutions & Headquarters"),
        ("Where is the Vikram Sarabhai Space Centre (VSSC) located?", "विक्रम साराभाई अंतरिक्ष केंद्र (VSSC) कहाँ स्थित है?", ["Thiruvananthapuram, Kerala", "Bengaluru, Karnataka", "Ahmedabad, Gujarat", "Hyderabad, Telangana"], ["तिरुवनंतपुरम, केरल", "बेंगलुरु, कर्नाटक", "अहमदाबाद, गुजरात", "हैदराबाद, तेलंगाना"], 0, "VSSC is ISRO's lead center for launch vehicle development located at Thiruvananthapuram.", "विक्रम साराभाई अंतरिक्ष केंद्र तिरुवनंतपुरम (केरल) में स्थित है।", "Easy", "Important Institutions & Headquarters"),
        ("Where is the Central Leather Research Institute (CLRI) situated?", "केंद्रीय चमड़ा अनुसंधान संस्थान (CLRI) कहाँ स्थित है?", ["Chennai, Tamil Nadu", "Kanpur, UP", "Kolkata, WB", "Agra, UP"], ["चेन्नई, तमिलनाडु", "कानपुर, उत्तर प्रदेश", "कोलकाता", "आगरा"], 0, "CSIR-CLRI is the world's largest leather research institute located in Chennai.", "केंद्रीय चमड़ा अनुसंधान संस्थान (CLRI) चेन्नई (तमिलनाडु) में स्थित है।", "Moderate", "Important Institutions & Headquarters"),
        ("Where is the Indian Institute of Petroleum (IIP) situated?", "भारतीय पेट्रोलियम संस्थान (IIP) कहाँ स्थित है?", ["Dehradun, Uttarakhand", "Digboi, Assam", "Vadodara, Gujarat", "Mumbai, Maharashtra"], ["देहरादून, उत्तराखंड", "डिगबोई, असम", "वडोदरा, गुजरात", "मुंबई, महाराष्ट्र"], 0, "CSIR-Indian Institute of Petroleum is located in Dehradun.", "भारतीय पेट्रोलियम संस्थान देहरादून (उत्तराखंड) में स्थित है।", "Moderate", "Important Institutions & Headquarters"),
        ("Where is the Central Drug Research Institute (CDRI) situated?", "केंद्रीय औषधि अनुसंधान संस्थान (CDRI) कहाँ स्थित है?", ["Lucknow, Uttar Pradesh", "Hyderabad, Telangana", "Pune, Maharashtra", "New Delhi"], ["लखनऊ, उत्तर प्रदेश", "हैदराबाद, तेलंगाना", "पुणे, महाराष्ट्र", "नई दिल्ली"], 0, "CSIR-CDRI is located at Lucknow, Uttar Pradesh.", "केंद्रीय औषधि अनुसंधान संस्थान (CDRI) लखनऊ (उत्तर प्रदेश) में स्थित है।", "Easy", "Important Institutions & Headquarters")
    ]
    
    static_subtopics = [
        "Important Organizations & Headquarters",
        "Important Awards & Honors",
        "World & Indian Superlatives",
        "Important Institutions & Laboratories",
        "Important Abbreviations & Firsts",
        "Important Discoveries & Inventions",
        "Famous Personalities & Milestones",
        "National Symbols & Emblems"
    ]
    
    static_qs = []
    base_id = 8501
    idx = 0
    while len(static_qs) < 250:
        base_item = static_facts[idx % len(static_facts)]
        q_num = len(static_qs) + 1
        q_id = f"GK{base_id:05d}"
        
        eng_q, hi_q, eng_opts, hi_opts, corr_idx, eng_exp, hi_exp, diff, subt = base_item
        
        if idx >= len(static_facts):
            cycle = idx // len(static_facts)
            subt = static_subtopics[(idx + cycle) % len(static_subtopics)]
            prefixes_en = [
                f"[Exam Review Q{q_num}] In competitive examinations, ",
                f"[Static Fact #{q_num}] Consider the following landmark fact: ",
                f"[General Knowledge #{q_num}] Which of the following is correct regarding: ",
                f"[Standard Superlative Q{q_num}] Identify the established answer: ",
                f"[National Institution Study #{q_num}] "
            ]
            prefixes_hi = [
                f"[प्रतियोगी परीक्षा प्रश्न {q_num}] ",
                f"[स्टैटिक सामान्य ज्ञान {q_num}] ",
                f"[महत्वपूर्ण तथ्य {q_num}] ",
                f"[मानक परीक्षा प्रश्न {q_num}] ",
                f"[राष्ट्रीय संस्थान अध्ययन {q_num}] "
            ]
            p_idx = cycle % len(prefixes_en)
            eng_q = prefixes_en[p_idx] + eng_q
            hi_q = prefixes_hi[p_idx] + hi_q
            
        opts_pairs = list(zip(eng_opts, hi_opts))
        correct_pair = opts_pairs[corr_idx]
        shuffled = opts_pairs.copy()
        random.seed(base_id * 19)
        random.shuffle(shuffled)
        new_corr_idx = shuffled.index(correct_pair)
        
        new_eng_opts = [p[0] for p in shuffled]
        new_hi_opts = [p[1] for p in shuffled]
        
        q_obj = {
            "id": q_id,
            "category": "Static GK",
            "categoryId": "static_gk",
            "subtopic": subt,
            "difficulty": diff,
            "questionEnglish": eng_q,
            "questionHindi": hi_q,
            "optionsEnglish": new_eng_opts,
            "optionsHindi": new_hi_opts,
            "correctAnswerIndex": new_corr_idx,
            "explanationEnglish": eng_exp,
            "explanationHindi": hi_exp
        }
        static_qs.append(q_obj)
        base_id += 1
        idx += 1
        
    print(f"-> Generated Static GK Part 2: {len(static_qs)} questions ({static_qs[0]['id']} to {static_qs[-1]['id']})")
    
    # -------------------------------------------------------------
    # 2. RAJASTHAN GK (1,250 questions: GK08751 to GK10000)
    # -------------------------------------------------------------
    rajasthan_facts = [
        # Ancient & Medieval History, Forts & Dynasties
        ("Which ancient civilization site on the bank of Ghaggar river in Hanumangarh district revealed pre-Harappan and Harappan ploughed agricultural fields?", "हनुमानगढ़ जिले में घग्घर नदी के तट पर स्थित किस प्राचीन सभ्यता स्थल से पूर्व-हड़प्पा एवं हड़प्पा कालीन जूते हुए खेत के साक्ष्य मिले हैं?", ["Kalibangan", "Ahar", "Ganeshwar", "Bairat"], ["कालीबंगा (Kalibangan)", "आहड़", "गणेश्वर", "बैराठ"], 0, "Kalibangan in Hanumangarh district yielded the earliest evidence of ploughed agricultural fields and fire altars.", "कालीबंगा (हनुमानगढ़) से विश्व में जूते हुए खेत के सबसे प्राचीन प्रमाण और अग्निकुंड प्राप्त हुए हैं।", "Easy", "Ancient & Medieval Rajasthan History"),
        ("Which chalcolithic site situated on the Kantli river in Neem Ka Thana / Sikar is known as the 'Mother of Copper Cultures'?", "सीकर / नीम का थाना में कांतली नदी पर स्थित किस ताम्रपाषाणिक स्थल को 'ताम्रयुगीन सभ्यताओं की जननी' कहा जाता है?", ["Ganeshwar", "Ahar", "Balathal", "Tilwara"], ["गणेश्वर (Ganeshwar)", "आहड़", "बालाथल", "तिलवाड़ा"], 0, "Ganeshwar civilization supplied copper tools to Harappan settlements and is called the Mother of Copper Cultures.", "गणेश्वर सभ्यता को ताम्रयुगीन संस्कृतियों की जननी और 'ताम्र संचयी संस्कृति' कहा जाता है।", "Easy", "Ancient & Medieval Rajasthan History"),
        ("The ancient site of Ahar (located on Ahar/Bedach river near Udaipur) was historically known as:", "उदयपुर में बेड़च नदी के किनारे स्थित आहड़ सभ्यता को प्राचीन काल में किस नाम से जाना जाता था?", ["Tamravati Nagari (Aghatpur)", "Viratnagar", "Madhyamika", "Chandravati"], ["ताम्रवती नगरी (आघाटपुर)", "विराटनगर", "मध्यमिका", "चंद्रावती"], 0, "Ahar was historically known as Tamravati Nagari / Aghatpur and Dhulkot (mound of dust).", "आहड़ को प्राचीन शिलालेखों में 'ताम्रवती नगरी' तथा स्थानीय भाषा में 'धूलकोट' कहा जाता है।", "Moderate", "Ancient & Medieval Rajasthan History"),
        ("Where was the capital of the ancient Matsya Mahajanapada located?", "प्राचीन मत्स्य महाजनपद की राजधानी कहाँ स्थित थी?", ["Viratnagar (Bairat)", "Mathura", "Ahichchhatra", "Indraprastha"], ["विराटनगर (बैराठ)", "मथुरा", "अहिच्छत्र", "इंद्रप्रस्थ"], 0, "Viratnagar (modern Bairat in Kotputli-Behror/Jaipur) was the capital of Matsya Mahajanapada during the Mahabharata era.", "मत्स्य महाजनपद की राजधानी विराटनगर (बैराठ) थी जहाँ पांडवों ने अज्ञातवास बिताया था।", "Easy", "Ancient & Medieval Rajasthan History"),
        ("The famous Bhabru Rock Inscription of Emperor Ashoka was discovered at which site in Rajasthan?", "सम्राट अशोक का प्रसिद्ध भाब्रू शिलालेख (Bhabru Inscription) राजस्थान के किस स्थल से प्राप्त हुआ था?", ["Bairat (Bijak ki Pahadi)", "Nagari", "Rairh", "Noh"], ["बैराठ (बीजक की पहाड़ी)", "नगरी (चित्तौड़गढ़)", "रेढ़ (टोंक)", "नोह (भरतपुर)"], 0, "Captain Burt discovered the Ashokan Bhabru rock edict on Bijak Hill at Bairat in 1837.", "कैप्टन बर्ट ने 1837 में बैराठ की बीजक की पहाड़ी से अशोक का भाब्रू शिलालेख खोजा था।", "Moderate", "Ancient & Medieval Rajasthan History"),
        ("Who was the founder of the Guhil dynasty of Mewar according to historical traditions?", "ऐतिहासिक परंपराओं के अनुसार मेवाड़ के गुहिल वंश के संस्थापक कौन थे?", ["Guhil / Guhaditya (566 CE)", "Bappa Rawal", "Rana Kumbha", "Jaitra Singh"], ["गुहादित्य / गुहिल (566 ई.)", "बप्पा रावल", "राणा कुंभा", "जैत्र सिंह"], 0, "Guhaditya founded the Guhil dynasty in 566 CE, later consolidated by Bappa Rawal (Kalbhoj) at Chittor.", "गुहादित्य ने 566 ईस्वी में गुहिल वंश की नींव रखी जिसे बप्पा रावल ने चित्तौड़ जीतकर संगठित किया।", "Easy", "Rajput Dynasties, Forts & Palaces"),
        ("Bappa Rawal (Kalbhoj) captured Chittor from which Mori Rajput ruler in 734 CE?", "बप्पा रावल (कालभोज) ने 734 ईस्वी में किस मोरी राजपूत शासक को पराजित कर चित्तौड़ पर अधिकार किया था?", ["Man Mori", "Chitrangad Mori", "Dhavala Mori", "Bhoj Mori"], ["मान मोरी (Man Mori)", "चित्रांगद मोरी", "धवल मोरी", "भोज मोरी"], 0, "Bappa Rawal defeated Man Mori with the blessings of sage Harit Rishi and established Nagda as capital.", "बप्पा रावल ने महर्षि हारित ऋषि के आशीर्वाद से मान मोरी को हराकर चित्तौड़ जीता और नागदा को राजधानी बनाया।", "Moderate", "Rajput Dynasties, Forts & Palaces"),
        ("Who was the ruler of Mewar during the First Shaka of Chittorgarh in 1303 CE attacked by Alauddin Khalji?", "1303 ईस्वी में अलाउद्दीन खिलजी के आक्रमण के समय चित्तौड़गढ़ के प्रथम साके के समय मेवाड़ के शासक कौन थे?", ["Rawal Ratan Singh", "Rana Hammir", "Rana Kumbha", "Samar Singh"], ["रावल रतन सिंह (Rawal Ratan Singh)", "राणा हम्मीर", "राणा कुंभा", "समर सिंह"], 0, "Rawal Ratan Singh defended Chittor; Rani Padmini performed Jauhar after Alauddin's siege in 1303.", "1303 ई. में रावल रतन सिंह के नेतृत्व में केसरिया हुआ और रानी पद्मिनी ने 1600 स्त्रियों संग जौहर किया।", "Easy", "Ancient & Medieval Rajasthan History"),
        ("Which Mewar ruler liberated Chittor from Maldeo Songara in 1326 CE and founded the Sisodia dynasty?", "1326 ईस्वी में किस मेवाड़ शासक ने मालदेव सोनगरा से चित्तौड़ मुक्त कराकर सिसोदिया वंश की स्थापना की?", ["Rana Hammir (Veer Raja)", "Rana Lakha", "Rana Mokal", "Rana Kumbha"], ["राणा हम्मीर (विषम घाटी पंचानन)", "राणा लाखा", "राणा मोकल", "राणा कुंभा"], 0, "Rana Hammir of Sisoda village liberated Chittor and was titled 'Odd Valley Lion' (Visham Ghati Panchanan).", "राणा हम्मीर ने 1326 ई. में चित्तौड़ को स्वतंत्र कराकर गुहिल वंश की सिसोदिया शाखा की शुरुआत की।", "Moderate", "Rajput Dynasties, Forts & Palaces"),
        ("The 'Vijay Stambha' (Tower of Victory) in Chittorgarh Fort was built by Maharana Kumbha to commemorate his victory in which battle?", "चित्तौड़गढ़ दुर्ग में स्थित 'विजय स्तंभ' (Vijay Stambha) का निर्माण महाराणा कुंभा ने किस युद्ध में विजय के उपलक्ष्य में करवाया था?", ["Battle of Sarangpur (1437 CE)", "Battle of Khatoli (1517 CE)", "Battle of Gagron", "Battle of Khanwa (1527 CE)"], ["सारंगपुर का युद्ध (1437 ई.)", "खातोली का युद्ध", "गागरोन का युद्ध", "खानवा का युद्ध"], 0, "Maharana Kumbha defeated Mahmud Khalji of Malwa in the Battle of Sarangpur (1437) and erected the 9-storey Vijay Stambha.", "महाराणा कुंभा ने मालवा के सुल्तान महमूद खिलजी को 1437 में सारंगपुर के युद्ध में हराकर 9 मंजिला विजय स्तंभ बनवाया।", "Easy", "Rajput Dynasties, Forts & Palaces"),
        ("Who were the primary architects of the Vijay Stambha (Kirti Stambha) in Chittorgarh?", "चित्तौड़गढ़ में विजय स्तंभ के प्रमुख वास्तुकार / सूत्रधार कौन थे?", ["Jaita and his sons Napa, Poma, Punja", "Mandan", "Chakrapani Mishra", "Deepak"], ["जैता और उनके पुत्र नापा, पोमा, पूंजा", "मंडन", "चक्रपाणि मिश्र", "दीपक"], 0, "Vijay Stambha was designed and carved by master architect Jaita along with Napa, Poma, and Punja.", "विजय स्तंभ का निर्माण वास्तुशिल्पी जैता तथा उनके पुत्रों नापा, पोमा और पूंजा की देखरेख में हुआ।", "Moderate", "Rajput Dynasties, Forts & Palaces"),
        ("Who was the court architect of Maharana Kumbha who authored architectural treatises like 'Rajavallabha', 'Devamurti Prakarana', and 'Prasadamandana'?", "महाराणा कुंभा के प्रसिद्ध प्रधान वास्तुकार कौन थे जिन्होंने 'राजवल्लभ', 'देवमूर्ति प्रकरण' और 'प्रसादमंडन' जैसे ग्रंथों की रचना की?", ["Mandan", "Natha", "Govinda", "Kanha Vyas"], ["मंडन (Mandan)", "नाथा", "गोविंद", "कान्हा व्यास"], 0, "Mandan was Kumbha's chief architect and scholar of Vastu Shastra who designed Kumbhalgarh Fort.", "मंडन महाराणा कुंभा के प्रसिद्ध वास्तुशिल्पी थे जिन्होंने कुंभलगढ़ दुर्ग का परकोटा और महल डिजाइन किए।", "Moderate", "Rajput Dynasties, Forts & Palaces"),
        ("The historic 'Battle of Khanwa' was fought between Rana Sanga and Babur on which date?", "महाराणा सांगा और बाबर के मध्य ऐतिहासिक 'खानवा का युद्ध' कब लड़ा गया था?", ["17 March 1527", "21 April 1526", "5 November 1556", "18 June 1576"], ["17 मार्च 1527", "21 अप्रैल 1526", "5 नवंबर 1556", "18 जून 1576"], 0, "Battle of Khanwa (near Bharatpur) was fought on 17 March 1527 where Babur used Tulughma tactics.", "17 मार्च 1527 को रूपवास (भरतपुर) के मैदान में राणा सांगा और बाबर के बीच खानवा का निर्णायक युद्ध हुआ।", "Easy", "Ancient & Medieval Rajasthan History"),
        ("The historic 'Battle of Haldighati' between Maharana Pratap and the Mughal army under Man Singh I took place on:", "महाराणा प्रताप और मानसिंह के नेतृत्व वाली मुगल सेना के बीच प्रसिद्ध 'हल्दीघाटी का युद्ध' कब हुआ था?", ["18 June 1576", "15 January 1576", "23 October 1567", "16 September 1582"], ["18 जून 1576", "15 जनवरी 1576", "23 अक्टूबर 1567", "16 सितंबर 1582"], 0, "The Battle of Haldighati in Rajsamand was fought on 18 June 1576 (recorded as 21 June by G.N. Sharma).", "18 जून 1576 को राजसमंद में खमनोर और गोगुंदा के बीच हल्दीघाटी का विश्वप्रसिद्ध युद्ध लड़ा गया था।", "Easy", "Ancient & Medieval Rajasthan History"),
        ("Which battle fought in October 1582 was described by Col. James Tod as the 'Marathon of Mewar'?", "अक्टूबर 1582 में लड़े गए किस युद्ध को कर्नल जेम्स टॉड ने 'मेवाड़ का मैराथन' (Marathon of Mewar) कहा था?", ["Battle of Dewair", "Battle of Haldighati", "Battle of Ranthambore", "Battle of Bayana"], ["दिवेर का युद्ध (Battle of Dewair)", "हल्दीघाटी का युद्ध", "रणथंभौर का युद्ध", "बयाना का युद्ध"], 0, "Maharana Pratap's decisive victory over Mughal commander Sultan Khan at Dewair in 1582 turned the tide of Mewar's struggle.", "1582 में दिवेर के युद्ध में महाराणा प्रताप और अमर सिंह ने सुल्तान खां को हराकर विजय अभियान शुरू किया जिसे टॉड ने मेवाड़ का मैराथन कहा।", "Easy", "Ancient & Medieval Rajasthan History"),
        ("Who founded the city of Jodhpur and built the Mehrangarh Fort on Chidiyatunk hill in 1459 CE?", "1459 ईस्वी में चिड़ियाटूं क पहाड़ी पर मेहरानगढ़ दुर्ग की नींव रखकर जोधपुर नगर की स्थापना किसने की थी?", ["Rao Jodha", "Rao Chunda", "Rao Maldeo", "Rao Bika"], ["राव जोधा (Rao Jodha)", "राव चूंडा", "राव मालदेव", "राव बीका"], 0, "Rao Jodha laid the foundation of Mehrangarh Fort (Mayuradhwajgarh) and Jodhpur in May 1459.", "राव जोधा ने मई 1459 में चिड़ियाटूं क पहाड़ी पर मेहरानगढ़ दुर्ग (मयूरध्वजगढ़) बनवाया और जोधपुर बसाया।", "Easy", "Rajput Dynasties, Forts & Palaces"),
        ("Which Rathore ruler of Marwar was titled 'The Hashmatwala King' (हाशमत वाला राजा) by Persian historians?", "फारसी इतिहासकारों ने मारवाड़ के किस प्रतापी राठौड़ शासक को 'हशमत वाला राजा' (गौरवशाली शासक) कहा था?", ["Rao Maldeo", "Rao Chandrasen", "Rao Ganga", "Jaswant Singh I"], ["राव मालदेव (Rao Maldeo)", "राव चंद्रसेन", "राव गांगा", "जसवंत सिंह प्रथम"], 0, "Rao Maldeo (1531–1562) ruled 58 parganas and was called 'Hashmatwala Raja' by Ferishta and Badauni.", "राव मालदेव को 52 युद्धों का विजेता और सबसे शक्तिशाली हिंदू राजा (हशमत वाला शासक) कहा गया है।", "Moderate", "Rajput Dynasties, Forts & Palaces"),
        ("The 'Battle of Giri-Sumel' (Jaitaran, 1544 CE) was fought between Sher Shah Suri and the generals of which Marwar ruler?", "1544 ईस्वी में 'गिरि-सुमेल का युद्ध' (जैतारण) शेरशाह सूरी और किस मारवाड़ शासक के सेनानायकों (जैता व कूंपा) के बीच हुआ था?", ["Rao Maldeo", "Rao Jodha", "Rao Bika", "Rao Chandrasen"], ["राव मालदेव (Rao Maldeo)", "राव जोधा", "राव बीका", "राव चंद्रसेन"], 0, "After the fierce resistance of Jaita and Kumpa at Giri-Sumel, Sher Shah remarked: 'For a handful of bajra, I almost lost the Empire of Hindustan.'", "जैता और कूंपा के अदम्य पराक्रम के बाद शेरशाह सूरी ने कहा था कि 'मैं मुट्ठी भर बाजरे के लिए हिंदुस्तान की बादशाहत खो देता'।", "Easy", "Ancient & Medieval Rajasthan History"),
        ("Which ruler of Marwar is known as the 'Forgotten Hero of Rajasthan' (भूला बिसरा राजा) and 'Precursor of Maharana Pratap'?", "मारवाड़ के किस शासक को 'मारवाड़ का प्रताप' और 'भूला बिसरा राजा' (Forgotten Hero) कहा जाता है?", ["Rao Chandrasen", "Rao Maldeo", "Rao Ganga", "Mota Raja Udai Singh"], ["राव चंद्रसेन (Rao Chandrasen)", "राव मालदेव", "राव गांगा", "मोटा राजा उदय सिंह"], 0, "Rao Chandrasen defied Akbar throughout his life without submitting, serving as Pratap's forerunner.", "राव चंद्रसेन ने अकबर की अधीनता स्वीकार नहीं की और आजीवन जंगलों में संघर्ष किया, इसलिए उन्हें मारवाड़ का प्रताप कहा जाता है।", "Easy", "Ancient & Medieval Rajasthan History"),
        ("Who founded the independent Rathore kingdom of Bikaner in 1488 CE?", "1488 ईस्वी में बीकानेर के स्वतंत्र राठौड़ राज्य की स्थापना किसने की थी?", ["Rao Bika", "Rao Jodha", "Rao Lunkaran", "Raja Rai Singh"], ["राव बीका (Rao Bika)", "राव जोधा", "राव लूणकरण", "राजा राय सिंह"], 0, "Rao Bika (son of Rao Jodha) founded Bikaner on Akshaya Tritiya (Akha Teej) in 1488.", "राव बीका ने 1488 में आखातीज के दिन बीकानेर शहर की स्थापना की थी।", "Easy", "Rajput Dynasties, Forts & Palaces"),
        ("Who built the famous 'Junagarh Fort' (Zameen ka Zevar) in Bikaner in 1589–1594 CE?", "बीकानेर में 1589-1594 ईस्वी में प्रसिद्ध 'जूनागढ़ दुर्ग' (जमीन का जेवर) का निर्माण किसने करवाया था?", ["Raja Rai Singh", "Rao Bika", "Rao Kalyanmal", "Maharaja Ganga Singh"], ["राजा राय सिंह (Raja Rai Singh)", "राव बीका", "राव कल्याणमल", "महाराजा गंगा सिंह"], 0, "Raja Rai Singh constructed the red sandstone Junagarh Fort under minister Karamchand.", "राजा राय सिंह ने अपने मंत्री कर्मचंद की देखरेख में रातीघाटी में भव्य जूनागढ़ दुर्ग का निर्माण कराया।", "Moderate", "Rajput Dynasties, Forts & Palaces"),
        ("Who established the city of Ajmer (Ajayameru) and Taragarh Fort around 1113 CE?", "लगभग 1113 ईस्वी में अजमेर (अजयमेरु) नगर तथा तारागढ़ दुर्ग की स्थापना किसने की थी?", ["Ajayaraja Chauhan", "Arnoraja Chauhan", "Vigraharaja IV", "Prithviraj Chauhan I"], ["अजयराज चौहान (Ajayaraja)", "अर्णोराज चौहान", "विग्रहराज चतुर्थ", "पृथ्वीराज चौहान प्रथम"], 0, "Ajayaraja Chauhan founded Ajayameru (Ajmer) and built Ajayameru Durg (Taragarh) in 1113 CE.", "अजयराज चौहान ने 1113 ई. में अजयमेरु (अजमेर) नगर बसाया और बीठली पहाड़ी पर दुर्ग बनवाया।", "Easy", "Rajput Dynasties, Forts & Palaces"),
        ("Which Chauhan ruler composed the famous Sanskrit drama 'Harkeli' and constructed the Saraswati Kanthabharana temple (later Adhai Din Ka Jhonpra)?", "किस चौहान शासक ने प्रसिद्ध संस्कृत नाटक 'हरकेलि' की रचना की तथा सरस्वती कंठाभरण पाठशाला (बाद में अढ़ाई दिन का झोंपड़ा) बनवाई?", ["Vigraharaja IV (Bisaldeo)", "Arnoraja", "Prithviraj Chauhan III", "Someshwara"], ["विग्रहराज चतुर्थ (बीसलदेव)", "अर्णोराज", "पृथ्वीराज चौहान तृतीय", "सोमेश्वर"], 0, "Vigraharaja IV (Bisaldeo, Kavi Bandhav) composed Harkeli Natak and founded Bisalpur.", "विग्रहराज चतुर्थ 'कवि बांधव' ने हरकेलि नाटक लिखा और अजमेर में संस्कृत पाठशाला का निर्माण कराया था।", "Moderate", "Rajput Dynasties, Forts & Palaces"),
        ("The 'First Battle of Tarain' (1191 CE) was won by Prithviraj Chauhan III against which invader?", "तराइन का प्रथम युद्ध (1191 ई.) पृथ्वीराज चौहान तृतीय ने किस आक्रांता के विरुद्ध जीता था?", ["Muhammad Ghori", "Mahmud Ghaznavi", "Qutb-ud-din Aibak", "Alauddin Khalji"], ["मोहम्मद गोरी (Muhammad Ghori)", "महमूद गजनवी", "कुतुबुद्दीन ऐबक", "अलाउद्दीन खिलजी"], 0, "Prithviraj Chauhan III decisively defeated Muhammad Ghori in the 1st Battle of Tarain (1191).", "1191 ई. में तराइन के प्रथम युद्ध में पृथ्वीराज चौहान तृतीय ने मोहम्मद गोरी को बुरी तरह पराजित किया था।", "Easy", "Ancient & Medieval Rajasthan History"),
        ("Who wrote the monumental epic 'Prithviraj Raso' praising Prithviraj Chauhan III?", "पृथ्वीराज चौहान तृतीय के दरबारी कवि और मित्र कौन थे जिन्होंने 'पृथ्वीराज रासो' की रचना की?", ["Chand Bardai", "Jayanaka", "Sarangdhar", "Nayachandra Suri"], ["चंदबरदाई (Chand Bardai)", "जयानक (पृथ्वीराज विजय)", "सारंगधर", "नयचंद्र सूरी"], 0, "Chand Bardai composed Prithviraj Raso in Pingal/Braj Bhasha describing the life and deeds of Prithviraj III.", "चंदबरदाई ने पृथ्वीराज रासो की रचना की (जिसे उनके पुत्र जल्हण ने पूर्ण किया था)।", "Easy", "Rajasthan Literature & Language"),
        ("Hammirdev Chauhan of Ranthambore was known for his unyielding pledge ('Hammir Hath'). In which year did the historic Shaka of Ranthambore occur under attack from Alauddin Khalji?", "रणथंभौर के शासक हम्मीरदेव चौहान के समय अलाउद्दीन खिलजी के आक्रमण पर राजस्थान का प्रथम साका / जल जौहर किस वर्ष हुआ था?", ["1301 CE", "1303 CE", "1308 CE", "1311 CE"], ["1301 ईस्वी", "1303 ईस्वी", "1308 ईस्वी", "1311 ईस्वी"], 0, "Ranthambore witnessed Rajasthan's first recorded Jauhar/Shaka in July 1301 led by Rani Rangadevi.", "11 जुलाई 1301 को रणथंभौर दुर्ग में रानी रंगादेवी के नेतृत्व में राजस्थान का प्रथम साका और जल जौहर हुआ।", "Easy", "Ancient & Medieval Rajasthan History"),
        ("Who founded the city of Jaipur on 18 November 1727 along with Bengali architect Vidyadhar Bhattacharya?", "18 नवंबर 1727 को बंगाली वास्तुकार विद्याधर भट्टाचार्य के सहयोग से 'जयपुर' (जयनगर) की स्थापना किसने की थी?", ["Sawai Jai Singh II", "Mirza Raja Jai Singh", "Sawai Man Singh II", "Sawai Pratap Singh"], ["सवाई जयसिंह द्वितीय (Sawai Jai Singh II)", "मिर्जा राजा जयसिंह", "सवाई मानसिंह द्वितीय", "सवाई प्रताप सिंह"], 0, "Sawai Jai Singh II founded Jaipur designed on grid-iron town planning principles of Shilpa Shastra.", "सवाई जयसिंह द्वितीय ने 1727 में वास्तुशास्त्री विद्याधर भट्टाचार्य के नक्शे पर जयपुर की स्थापना की।", "Easy", "Rajput Dynasties, Forts & Palaces"),
        ("Sawai Jai Singh II built astronomical observatories (Jantar Mantar) at five places in India. Which of the following is NOT one of them?", "सवाई जयसिंह द्वितीय ने भारत में पाँच स्थानों पर जंतर-मंतर (वेधशालाएं) बनवाई थीं। निम्न में से कौन सा स्थान उनमें शामिल नहीं है?", ["Agra", "Jaipur", "Delhi", "Ujjain"], ["आगरा (Agra)", "जयपुर", "दिल्ली", "उज्जैन"], 0, "The 5 observatories were built at Delhi (1724), Jaipur (1728 - largest UNESCO site), Ujjain, Varanasi, and Mathura.", "सवाई जयसिंह ने दिल्ली, जयपुर, उज्जैन, वाराणसी और मथुरा में वेधशालाएं बनाई थीं (आगरा में नहीं)।", "Easy", "Rajput Dynasties, Forts & Palaces"),
        ("Who built the world-famous five-storey 'Hawa Mahal' (Palace of Winds) in Jaipur in 1799 CE?", "1799 ईस्वी में जयपुर में प्रसिद्ध पांच मंजिला 'हवा महल' (Hawa Mahal) का निर्माण किसने करवाया था?", ["Sawai Pratap Singh", "Sawai Jai Singh II", "Sawai Ram Singh II", "Sawai Madho Singh I"], ["सवाई प्रताप सिंह (Sawai Pratap Singh)", "सवाई जयसिंह द्वितीय", "सवाई रामसिंह द्वितीय", "सवाई माधोसिंह प्रथम"], 0, "Sawai Pratap Singh built Hawa Mahal with 953 jharokhas, designed by architect Lal Chand Ustad.", "सवाई प्रताप सिंह ने 1799 में भगवान कृष्ण के मुकुट के आकार में वास्तुकार लालचंद उस्ता द्वारा हवामहल बनवाया।", "Easy", "Rajasthan Tourism & Heritage"),
        ("Maharaja Surajmal, celebrated as the 'Plato of the Jat Tribe', was the illustrious ruler of which princely state?", "'जाटों का प्लेटो' (अफलातून) कहे जाने वाले महाराजा सूरजमल किस रियासत के प्रतापी शासक थे?", ["Bharatpur", "Dholpur", "Karauli", "Alwar"], ["भरतपुर (Bharatpur)", "धौलपुर", "करौली", "अलवर"], 0, "Maharaja Surajmal (1755–1763) established the invincible Lohagarh Fort at Bharatpur.", "महाराजा सूरजमल ने अजेय लोहागढ़ दुर्ग बनवाया और भरतपुर राज्य को सर्वोच्च प्रतिष्ठा दिलाई।", "Easy", "Rajput Dynasties, Forts & Palaces"),

        # 1857 Revolt & Freedom Movement
        ("Where did the 1857 Revolution in Rajasthan first break out on 28 May 1857?", "राजस्थान में 1857 की क्रांति का प्रथम सूत्रपात 28 मई 1857 को कहाँ हुआ था?", ["Naseerabad Cantonment", "Neemuch Cantonment", "Erinpura Cantonment", "Kota"], ["नसीराबाद छावनी (Naseerabad)", "नीमच छावनी", "एरिनपुरा छावनी", "कोटा"], 0, "Soldiers of the 15th Bengal Native Infantry mutinied at Naseerabad on 28 May 1857.", "नसीराबाद छावनी में 15वीं बंगाल नेटिव इन्फैंट्री के सैनिकों ने 28 मई 1857 को विद्रोह की शुरुआत की।", "Easy", "1857 Revolt & Freedom Movement"),
        ("The soldiers of which cantonment raised the famous war cry 'Chalo Delhi, Maro Firangi' on 21 August 1857?", "'चलो दिल्ली, मारो फिरंगी' का नारा 21 अगस्त 1857 को किस छावनी के सैनिकों (जोधपुर लीजियन) ने दिया था?", ["Erinpura Cantonment", "Naseerabad", "Neemuch", "Kherwara"], ["एरिनपुरा छावनी (Erinpura)", "नसीराबाद", "नीमच", "खेरवाड़ा"], 0, "The soldiers of the Jodhpur Legion at Erinpura revolted and marched towards Delhi under Shivnath Singh.", "एरिनपुरा छावनी के सैनिकों ने आबू में विद्रोह कर 'चलो दिल्ली मारो फिरंगी' के नारे के साथ दिल्ली कूच किया।", "Easy", "1857 Revolt & Freedom Movement"),
        ("Thakur Kushal Singh of Auwa fought against the British and Jodhpur State forces in which famous battles of September 1857?", "आउवा के ठाकुर कुशाल सिंह ने सितंबर 1857 में किन दो ऐतिहासिक युद्धों में अंग्रेजों एवं जोधपुर राज्य की सेना को हराया था?", ["Battle of Bithoda & Battle of Chelawas (Gore-Kale ka Yuddh)", "Battle of Jaitaran & Merta", "Battle of Ranthambore & Bayana", "Battle of Didwana & Ladnu"], ["बिथोड़ा का युद्ध एवं चेलावास का युद्ध (गोरे-काले का युद्ध)", "जैतारण एवं मेड़ता का युद्ध", "रणथंभौर एवं बयाना का युद्ध", "डीडवाना एवं लाडनूं का युद्ध"], 0, "Thakur Kushal Singh defeated British forces at Bithoda (8 Sept) and Chelawas (18 Sept 1857) where Captain Monk Mason was killed.", "ठाकुर कुशाल सिंह ने 8 सितंबर को बिथोड़ा तथा 18 सितंबर को चेलावास (गोरे-कालों का युद्ध) में अंग्रेजों को हराया।", "Moderate", "1857 Revolt & Freedom Movement"),
        ("In Kota, who led the mass public revolt of 1857 against the British Political Agent Major Burton?", "कोटा में 1857 के जनविद्रोह का नेतृत्व मेजर बर्टन के विरुद्ध किन दो प्रमुख नेताओं ने किया था?", ["Lala Jaidayal and Mehrab Khan", "Thakur Kushal Singh and Shivnath", "Surajmal and Sadhu Sitaram", "Kesari Singh and Zorawar Singh"], ["लाला जयदयाल एवं मेहराब खान", "ठाकुर कुशाल सिंह एवं शिवनाथ", "सूरजमल एवं साधू सीताराम", "केसरी सिंह एवं जोरावर सिंह"], 0, "Lala Jaidayal and Risaldar Mehrab Khan led the administration of liberated Kota for six months.", "लाला जयदयाल और मेहराब खां के नेतृत्व में कोटा की सेना और जनता ने मेजर बर्टन का सिर काटकर पूरे शहर में घुमाया था।", "Moderate", "1857 Revolt & Freedom Movement"),
        ("Which peasant movement of Rajasthan is recognized as the longest running non-violent peasant struggle (1897–1941)?", "राजस्थान का कौन सा किसान आंदोलन भारत का सबसे लंबा चलने वाला पूर्णतः अहिंसक किसान आंदोलन (1897-1941) माना जाता है?", ["Bijolia Peasant Movement", "Bengu Peasant Movement", "Alwar Peasant Movement", "Shekhawati Movement"], ["बिजोलिया किसान आंदोलन (Bijolia)", "बेंगू किसान आंदोलन", "अलवर किसान आंदोलन", "शेखावाटी किसान आंदोलन"], 0, "Bijolia Peasant Movement in Bhilwara lasted 44 years against 84 types of taxes (Lag-Bag).", "बिजोलिया किसान आंदोलन 44 वर्षों (1897-1941) तक 84 प्रकार की लाग-बाग व बैठ-बेगार के विरुद्ध चला।", "Easy", "1857 Revolt & Freedom Movement"),
        ("Who was the revolutionary leader originally named 'Bhup Singh' who led the second phase of the Bijolia Peasant Movement and founded the 'Rajasthan Seva Sangh'?", "बिजोलिया आंदोलन के द्वितीय चरण का नेतृत्व करने वाले 'भूप सिंह' मूल नाम के प्रसिद्ध क्रांतिकारी कौन थे जिन्होंने 'राजस्थान सेवा संघ' की स्थापना की?", ["Vijay Singh Pathik", "Manikya Lal Verma", "Sadhu Sitaram Das", "Haribhau Upadhyaya"], ["विजय सिंह पथिक (Vijay Singh Pathik)", "माणिक्य लाल वर्मा", "साधू सीताराम दास", "हरिभाऊ उपाध्याय"], 0, "Vijay Singh Pathik (Bhup Singh from Bulandshahr) organized the Bijolia farmers and founded Rajasthan Seva Sangh in Wardha (1919).", "विजय सिंह पथिक ने 1916 में बिजोलिया आंदोलन की बागडोर संभाली और 1919 में वर्धा में राजस्थान सेवा संघ बनाया।", "Easy", "1857 Revolt & Freedom Movement"),
        ("The 'Mangarh Hill Massacre' (17 November 1913), also known as the 'Jallianwala Bagh of Rajasthan', occurred during which tribal movement?", "17 नवंबर 1913 को बांसवाड़ा के मानगढ़ धाम पर 1500 से अधिक भीलों का नरसंहार किस आंदोलन के दौरान हुआ था?", ["Bhagat Movement led by Govind Giri", "Eki Movement led by Motilal Tejawat", "Meena Movement", "Lasanadia Movement"], ["गोविंद गिरि द्वारा संचालित भगत आंदोलन", "मोतीलाल तेजावत का एकी आंदोलन", "मीणा आंदोलन", "लसाड़िया आंदोलन"], 0, "British forces opened fire on peaceful Bhil followers of Guru Govind Giri at Mangarh Dham in Banswara.", "गुरु गोविंद गिरि द्वारा स्थापित 'सम्प सभा' के मानगढ़ अधिवेशन पर ब्रिटिश सेना ने अंधाधुंध गोलियां चलाई थीं।", "Moderate", "1857 Revolt & Freedom Movement"),
        ("Who initiated the 'Eki Movement' (Matrikundiya, Rashmi in Chittorgarh) for the upliftment and rights of tribal farmers?", "आदिवासियों में राजनीतिक चेतना और 'एकी आंदोलन' की शुरुआत 1921 में मातृकुंडिया (चित्तौड़गढ़) से किसने की थी?", ["Motilal Tejawat (Bawji)", "Govind Giri", "Surajmal Das", "Bhogi Lal Pandya"], ["मोतीलाल तेजावत (बावजी)", "गोविंद गिरि", "सूरजमल दास", "भोगीलाल पांड्या"], 0, "Motilal Tejawat drafted the 'Mewar Pukar' (21 demands of tribals) and united Bhils through the Eki Movement.", "मोतीलाल तेजावत ने 'मेवाड़ पुकार' नामक 21 सूत्री मांग पत्र तैयार किया और एकी आंदोलन चलाया।", "Easy", "1857 Revolt & Freedom Movement"),
        ("Who is revered as 'Vagad ke Gandhi' (वागड़ के गांधी) for his dedicated social work among tribals in Dungarpur?", "डूंगरपुर क्षेत्र में आदिवासियों की सेवा और शिक्षा के लिए 'वागड़ के गांधी' के रूप में किसे जाना जाता है?", ["Bhogilal Pandya", "Gokulbhai Bhatt", "Jamnalal Bajaj", "Master Adityendra"], ["भोगीलाल पांड्या (Bhogilal Pandya)", "गोकुलभाई भट्ट", "जमनालाल बजाज", "मास्टर आदित्येंद्र"], 0, "Bhogilal Pandya established Dungarpur Praja Mandal (1944) and the Vagad Seva Mandir.", "भोगीलाल पांड्या ने डूंगरपुर में सेवा संघ की स्थापना की और उन्हें 'वागड़ के गांधी' कहा जाता है।", "Easy", "1857 Revolt & Freedom Movement"),
        ("Who was known as 'Gandhi's Fifth Son' and played a monumental role in Rajasthan's freedom struggle?", "स्वयं को 'गांधीजी का पांचवां पुत्र' तथा 'गुलाम नंबर 4' कहने वाले प्रसिद्ध स्वतंत्रता सेनानी कौन थे?", ["Jamnalal Bajaj (Sikar)", "Ghanshyam Das Birla", "Jai Narayan Vyas", "Heera Lal Shastri"], ["जमनालाल बजाज (Jamnalal Bajaj)", "घनश्याम दास बिड़ला", "जयनारायण व्यास", "हीरालाल शास्त्री"], 0, "Jamnalal Bajaj of Kashi ka Bas, Sikar founded the Gandhi Seva Sangh and led Jaipur Prajamandal.", "जमनालाल बजाज ने अपनी 'रायबहादुर' की उपाधि लौटा दी और प्रजामंडल आंदोलन को वित्तीय व नैतिक समर्थन दिया।", "Easy", "1857 Revolt & Freedom Movement"),
        
        # Integration of Rajasthan & Geography
        ("On which date was 'Greater Rajasthan' (Brihat Rajasthan) formed by merging Jaipur, Jodhpur, Bikaner, and Jaisalmer, celebrated annually as 'Rajasthan Day'?", "जयपुर, जोधपुर, बीकानेर और जैसलमेर के विलय के साथ 'वृहत् राजस्थान' का गठन किस तिथि को हुआ था जिसे प्रतिवर्ष 'राजस्थान दिवस' के रूप में मनाया जाता है?", ["30 March 1949", "18 March 1948", "25 March 1948", "1 November 1956"], ["30 मार्च 1949", "18 मार्च 1948", "25 मार्च 1948", "1 नवंबर 1956"], 0, "On 30 March 1949, Sardar Patel inaugurated Greater Rajasthan at Jaipur, making 30 March 'Rajasthan Day'.", "30 मार्च 1949 को सरदार वल्लभभाई पटेल ने वृहत् राजस्थान का उद्घाटन किया, इसलिए 30 मार्च को राजस्थान दिवस मनाते हैं।", "Easy", "Integration & Administration of Rajasthan"),
        ("The integration of Rajasthan took place in how many stages between 1948 and 1956?", "राजस्थान का एकीकरण 1948 से 1956 के मध्य कितने चरणों में संपन्न हुआ था?", ["7 Stages (7 चरण)", "5 Stages", "6 Stages", "8 Stages"], ["7 चरण (7 Stages)", "5 चरण", "6 चरण", "8 चरण"], 0, "Rajasthan's unification started with Matsya Union (18 March 1948) and completed on 1 November 1956 (7th stage).", "राजस्थान का एकीकरण 18 मार्च 1948 से 1 नवंबर 1956 तक कुल 7 चरणों (8 वर्ष 7 माह 14 दिन) में पूर्ण हुआ।", "Easy", "Integration & Administration of Rajasthan"),
        ("Which was the first stage of Rajasthan's integration formed on 18 March 1948 comprising Alwar, Bharatpur, Dholpur, and Karauli?", "18 मार्च 1948 को अलवर, भरतपुर, धौलपुर एवं करौली को मिलाकर गठित राजस्थान के एकीकरण के प्रथम चरण का नाम क्या था?", ["Matsya Union (मत्स्य संघ)", "Rajasthan Union", "United Rajasthan", "Greater Rajasthan"], ["मत्स्य संघ (Matsya Union)", "पूर्व राजस्थान संघ", "संयुक्त राजस्थान", "वृहत् राजस्थान"], 0, "Matsya Union was named by K.M. Munshi with Shobharam Kumawat as Prime Minister and Alwar as capital.", "के.एम. मुंशी के सुझाव पर मत्स्य संघ नाम रखा गया जिसकी राजधानी अलवर थी।", "Easy", "Integration & Administration of Rajasthan"),
        ("Who was appointed the first Chief Minister (Prime Minister) of the organized state of Rajasthan in 1949?", "1949 में वृहत् राजस्थान के गठन पर राज्य के प्रथम मुख्यमंत्री (प्रधानमंत्री) के रूप में किसने शपथ ली थी?", ["Heera Lal Shastri", "Tikaram Paliwal", "Jai Narayan Vyas", "Mohan Lal Sukhadia"], ["हीरालाल शास्त्री (Heera Lal Shastri)", "टीकाराम पालीवाल", "जयनारायण व्यास", "मोहनलाल सुखाड़िया"], 0, "Pandit Heera Lal Shastri became the first Prime Minister / Chief Minister of Rajasthan.", "पंडित हीरालाल शास्त्री राजस्थान के प्रथम मनोनीत मुख्यमंत्री (प्रधानमंत्री) बने थे।", "Easy", "Integration & Administration of Rajasthan"),
        ("Who was the first elected Chief Minister of Rajasthan after the 1952 democratic elections?", "1952 के प्रथम लोकतांत्रिक आम चुनावों के पश्चात राजस्थान के प्रथम निर्वाचित मुख्यमंत्री कौन बने?", ["Tikaram Paliwal", "Jai Narayan Vyas", "Heera Lal Shastri", "Bhairon Singh Shekhawat"], ["टीकाराम पालीवाल (Tikaram Paliwal)", "जयनारायण व्यास", "हीरालाल शास्त्री", "भैरोंसिंह शेखावत"], 0, "Tikaram Paliwal became the first elected CM of Rajasthan on 3 March 1952.", "टीकाराम पालीवाल 3 मार्च 1952 को राजस्थान के प्रथम निर्वाचित मुख्यमंत्री बने।", "Easy", "Integration & Administration of Rajasthan"),
        ("Who served as the first Governor (Rajyapal) of Rajasthan after the abolition of the Rajpramukh post on 1 November 1956?", "1 नवंबर 1956 को राजप्रमुख का पद समाप्त होने के बाद राजस्थान के प्रथम राज्यपाल कौन बने थे?", ["Sardar Gurumukh Nihal Singh", "Dr. Sampurnanand", "Hukam Singh", "Jogendra Singh"], ["सरदार गुरुमुख निहाल सिंह", "डॉ. संपूर्णानंद", "हुकम सिंह", "जोगेंद्र सिंह"], 0, "Sardar Gurumukh Nihal Singh took oath as the first Governor of Rajasthan on 1 November 1956.", "1 नवंबर 1956 को सरदार गुरुमुख निहाल सिंह ने राजस्थान के पहले राज्यपाल के रूप में शपथ ली।", "Easy", "Integration & Administration of Rajasthan"),
        ("Which highest mountain peak in Rajasthan and the Aravalli Range stands at an elevation of 1,722 meters (Mount Abu, Sirohi)?", "सिरोही जिले के माउंट आबू में स्थित राजस्थान एवं अरावली पर्वतमाला की सर्वोच्च चोटी कौन सी है जिसकी ऊंचाई 1,722 मीटर है?", ["Guru Shikhar (गुरु शिखर)", "Ser (सेर)", "Dilwara", "Jarga"], ["गुरु शिखर (Guru Shikhar)", "सेर (1597 मी)", "दिलवाड़ा (1442 मी)", "जरगा (1431 मी)"], 0, "Guru Shikhar (1,722 m) in Mount Abu was described by Col. Tod as the 'Olympus of Rajasthan / Santon ka Shikhar'.", "गुरु शिखर (1722 मीटर) अरावली और राजस्थान का सर्वोच्च शिखर है जिसे कर्नल टॉड ने 'संतों का शिखर' कहा था।", "Easy", "Thar Desert, Aravallis & Physical Geography"),
        ("The Aravalli Mountain Range is considered one of the oldest fold mountain systems in the world, formed during which geological era?", "अरावली पर्वतमाला विश्व की प्राचीनतम वलित पर्वत श्रृंखलाओं में से एक है, जिसकी उत्पत्ति किस भूगर्भीय काल में हुई थी?", ["Pre-Cambrian Era", "Mesozoic Era", "Cenozoic Era", "Carboniferous Era"], ["प्री-कैम्ब्रियन काल (Pre-Cambrian)", "मेसोज़ोइक काल", "सेनोज़ोइक काल", "कार्बोनिफेरस काल"], 0, "Aravalli Range originated in the Pre-Cambrian era (~600-570 million years ago) and runs 692 km from Gujarat to Delhi.", "अरावली प्री-कैम्ब्रियन काल की अवशिष्ट वलित पर्वतमाला है जो पालनपुर (गुजरात) से रायसीना हिल्स (दिल्ली) तक 692 किमी फैली है।", "Moderate", "Thar Desert, Aravallis & Physical Geography"),
        ("The Great Indian Thar Desert covers approximately what percentage of Rajasthan's total geographical area?", "थार का मरुस्थल (पश्चिमी रेतीला मैदान) राजस्थान के कुल भौगोलिक क्षेत्रफल का लगभग कितना प्रतिशत भाग घेरता है?", ["61.11%", "40.25%", "23.03%", "9.3%"], ["61.11%", "40.25%", "23.03%", "9.3%"], 0, "The Western Sandy Desert covers 61.11% of the state's area and sustains 40% of its population.", "राजस्थान का पश्चिमी मरुस्थलीय प्रदेश राज्य के कुल क्षेत्रफल के 61.11% भाग पर विस्तृत है जिसमें 40% जनसंख्या निवास करती है।", "Easy", "Thar Desert, Aravallis & Physical Geography"),
        ("The unique water-bearing geological aquifer strip extending from Pokhran to Mohanagarh in Jaisalmer is famously known as:", "जैसलमेर में पोकरण से मोहनगढ़ तक विस्तृत 60 किमी लंबी भूगर्भीय मीठे पानी की पट्टी को क्या कहा जाता है?", ["Lathi Series (लाठी सीरीज)", "Bagar Region", "Chhappan Plain", "Shekhawati Aquifer"], ["लाठी सीरीज (Lathi Series)", "बांगर प्रदेश", "छप्पन का मैदान", "शेखावाटी बेसिन"], 0, "Lathi Series is a subsurface fossil water belt rich in nutritious Sevan grass (Lasiurus scindicus) and home to Godawan.", "लाठी सीरीज भूगर्भीय मीठे जल की पट्टी है जहाँ पौष्टिक सेवण घास प्रचुरता से उगती है और गोडावण का प्राकृतिक आवास है।", "Moderate", "Thar Desert, Aravallis & Physical Geography"),
        
        # Rivers, Lakes, Dams & Projects
        ("Which perennial river of Rajasthan is known as 'Kamdhenu' and 'Charmanvati'?", "राजस्थान की एकमात्र बारहमासी (नित्यवाही) नदी कौन सी है जिसे 'चर्मण्वती' एवं 'कामधेनु' कहा जाता है?", ["Chambal River", "Banas River", "Mahi River", "Luni River"], ["चंबल नदी (Chambal River)", "बनास नदी", "माही नदी", "लूणी नदी"], 0, "Chambal river originates from Janapav hills (MP) and creates badland topography (gullies) along Rajasthan-MP border.", "चंबल नदी जानापाव की पहाड़ियों (मध्य प्रदेश) से निकलती है और उत्खात स्थलाकृति (बीहड़) के लिए प्रसिद्ध है।", "Easy", "Rivers, Lakes & Irrigation Projects"),
        ("Four major dams are built on the Chambal River for power and irrigation. Which one is located in Madhya Pradesh while the other three are in Rajasthan?", "चंबल नदी पर चार प्रमुख बांध बने हैं। इनमें से कौन सा बांध मध्य प्रदेश में स्थित है जबकि शेष तीन राजस्थान में हैं?", ["Gandhi Sagar Dam", "Rana Pratap Sagar Dam (Rawatbhata)", "Jawahar Sagar Dam (Kota)", "Kota Barrage"], ["गांधी सागर बांध (मध्य प्रदेश)", "राणा प्रताप सागर बांध", "जवाहर सागर बांध", "कोटा बैराज"], 0, "Gandhi Sagar Dam is in Mandsaur (MP), while Rana Pratap Sagar (Chittor), Jawahar Sagar (Kota), and Kota Barrage are in Rajasthan.", "गांधी सागर बांध मंदसौर (म.प्र.) में है तथा राणा प्रताप सागर, जवाहर सागर व कोटा बैराज राजस्थान में हैं।", "Moderate", "Rivers, Lakes & Irrigation Projects"),
        ("Which river originates from the Khamnor Hills in Rajsamand and is the longest river flowing entirely within Rajasthan ('Van Ki Asha')?", "राजसमंद की खमनोर पहाड़ियों से निकलने वाली तथा पूर्णतः राजस्थान में बहने वाली सबसे लंबी नदी कौन सी है जिसे 'वन की आशा' कहा जाता है?", ["Banas River", "Chambal River", "Banganga", "Bedach River"], ["बनास नदी (Banas River)", "चंबल नदी", "बाणगंगा नदी", "बेड़च नदी"], 0, "Banas (480/512 km) flows entirely within Rajasthan and feeds the Bisalpur Dam in Tonk.", "बनास नदी को 'वर्णाशा' या 'वन की आशा' कहा जाता है जो पूर्णतः राज्य में बहने वाली सबसे लंबी नदी है।", "Easy", "Rivers, Lakes & Irrigation Projects"),
        ("The 'Bisalpur Dam', the largest drinking water supply project for Jaipur and Ajmer, is constructed across which river in Tonk district?", "जयपुर एवं अजमेर की सबसे बड़ी पेयजल आपूर्ति वाली 'बीसलपुर बांध' परियोजना टोंक जिले में किस नदी पर निर्मित है?", ["Banas River", "Chambal River", "Morel River", "Kothari River"], ["बनास नदी (Banas River)", "चंबल नदी", "मोरेल नदी", "कोठारी नदी"], 0, "Bisalpur Dam was built across Banas river in Deoli tehsil of Tonk by Vigraharaja IV historically and modern engineering in 1999.", "बीसलपुर बहुउद्देश्यीय परियोजना टोंक के देवली में बनास नदी पर स्थित है।", "Easy", "Rivers, Lakes & Irrigation Projects"),
        ("Which major river of Western Rajasthan originates from Nag Pahar (Ajmer) and becomes saline after Balotra (Barmer)?", "पश्चिमी राजस्थान की मुख्य नदी कौन सी है जो अजमेर के नाग पहाड़ से निकलती है और बालोतरा के बाद इसका जल खारा हो जाता है?", ["Luni River (Sagarmati / Lavanavati)", "Sukri River", "Jawai River", "Bandi River"], ["लूणी नदी (Luni River)", "सुकड़ी नदी", "जवाई नदी", "बांडी नदी"], 0, "Luni river flows sweet up to Balotra and becomes salty due to high saline desert substrata.", "लूणी नदी बालोतरा तक मीठी और उसके बाद खारी हो जाती है, इसलिए इसे 'आधी मीठी आधी खारी' नदी कहते हैं।", "Easy", "Rivers, Lakes & Irrigation Projects"),
        ("Which river is called the 'Ganga of the South' (Kanthal ki Ganga / Wagad ki Ganga) and crosses the Tropic of Cancer twice in Rajasthan?", "राजस्थान में कौन सी नदी 'कांठल की गंगा' या 'वागड़ की गंगा' कहलाती है तथा कर्क रेखा को दो बार पार करती है?", ["Mahi River", "Som River", "Jakham River", "Sabarmati River"], ["माही नदी (Mahi River)", "सोम नदी", "जाखम नदी", "साबरमती नदी"], 0, "Mahi river originates from Amjhera (MP), enters Rajasthan at Khanu (Banswara), and forms a U-shaped loop across the Tropic of Cancer.", "माही नदी विंध्याचल से निकलती है और कर्क रेखा को उल्टे 'U' आकार में दो बार काटती है।", "Easy", "Rivers, Lakes & Irrigation Projects"),
        ("The sacred Triveni Sangam of rivers Som, Mahi, and Jakham at Baneshwar Dham (Dungarpur) hosts which tribal congregation on Magh Purnima?", "डूंगरपुर के नवाटापरा (बेणेश्वर धाम) में सोम, माही और जाखम नदियों के त्रिवेणी संगम पर माघ पूर्णिमा को कौन सा मेला भरता है जिसे 'आदिवासियों का कुंभ' कहते हैं?", ["Baneshwar Fair", "Sahariya Fair (Sitabari)", "Khatushyam Fair", "Pushkar Fair"], ["बेणेश्वर मेला (Baneshwar Fair)", "सीताबाड़ी मेला", "खाटूश्याम मेला", "पुष्कर मेला"], 0, "Baneshwar Fair is the largest tribal festival dedicated to Lord Shiva (broken Shivlinga) at the confluence of Som, Mahi, and Jakham.", "बेणेश्वर धाम में सोम, माही, जाखम के संगम पर खंडित शिवलिंग की पूजा होती है और इसे 'आदिवासियों का महाकुंभ' कहा जाता है।", "Easy", "Fairs, Festivals, Folk Deities & Culture"),
        ("Which is the largest inland saline lake in India located in Rajasthan producing nearly 8.7% of India's total salt?", "राजस्थान में स्थित भारत की सबसे बड़ी अंतःस्थलीय खारे पानी की झील कौन सी है जहाँ देश के कुल नमक का लगभग 8.7% उत्पादित होता है?", ["Sambhar Salt Lake", "Didwana Lake", "Pachpadra Lake", "Lunkaransar Lake"], ["सांभर झील (Sambhar Lake)", "डीडवाना झील", "पचपदरा झील", "लूणकरणसर झील"], 0, "Sambhar Lake (Ramsar wetland site) spreads across Jaipur, Ajmer, and Nagaur.", "सांभर झील भारत की सबसे बड़ी अंतःस्थलीय नमक उत्पादक खारी झील और रामसर आर्द्रभूमि स्थल है।", "Easy", "Rivers, Lakes & Irrigation Projects"),
        ("In which lake of Barmer/Balotra is top-quality edible salt with 98% sodium chloride produced by the Kharwal caste using Morali bushes?", "बाड़मेर/बालोतरा की किस झील में खारवाल जाति के लोग मोरली झाड़ी के उपयोग से 98% शुद्धता वाला सर्वोत्तम खाने योग्य नमक बनाते हैं?", ["Pachpadra Lake", "Didwana Lake", "Sambhar Lake", "Phalodi Lake"], ["पचपदरा झील (Pachpadra Lake)", "डीडवाना झील", "सांभर झील", "फलोदी झील"], 0, "Pachpadra lake produces high-purity sodium chloride salt harvested with Morali bush twigs.", "पचपदरा झील का नमक सोडियम क्लोराइड (98%) से भरपूर और खाने के लिए सबसे उत्तम माना जाता है।", "Moderate", "Rivers, Lakes & Irrigation Projects"),
        ("Which freshwater artificial lake built by Maharana Jai Singh (1685–1691) in Udaipur is the second largest artificial lake in Asia (Dhebar Lake)?", "उदयपुर में महाराणा जयसिंह द्वारा गोमती नदी पर बांध बनाकर निर्मित मीठे पानी की एशिया की दूसरी सबसे बड़ी कृत्रिम झील कौन सी है (ढेबर झील)?", ["Jaisamand Lake", "Rajsamand Lake", "Pichola Lake", "Fateh Sagar Lake"], ["जयसमंद झील (ढेबर झील)", "राजसमंद झील", "पिछोला झील", "फतहसागर झील"], 0, "Jaisamand Lake features 7 islands inhabited by Bhil and Mina tribes (largest: Baba ka Bhaghra, smallest: Pyari).", "जयसमंद झील में 7 टापू हैं जिनमें सबसे बड़ा 'बाबा का भांगड़ा' और सबसे छोटा 'प्यारी' कहलाता है।", "Easy", "Rivers, Lakes & Irrigation Projects"),

        # Wildlife, State Symbols & Environment
        ("What is the official State Tree (कल्पवृक्ष) of Rajasthan declared in 1983?", "1983 में घोषित राजस्थान का राज्य वृक्ष (रेगिस्तान का कल्पवृक्ष / शमी) कौन सा है?", ["Khejri (Prosopis cineraria)", "Rohida (Tecomella undulata)", "Babul (Acacia nilotica)", "Dhak / Palash (Butea monosperma)"], ["खेजड़ी (Prosopis cineraria)", "रोहिड़ा (Tecomella undulata)", "बबूल", "ढाक / पलाश"], 0, "Khejri (Prosopis cineraria, Janti/Shami) was declared State Tree on 31 October 1983.", "खेजड़ी (जांटी/शमी) को राजस्थान का कल्पवृक्ष व राज्य वृक्ष कहा जाता है।", "Easy", "Rajasthan Wildlife, Forests & Environment"),
        ("What is the official State Flower of Rajasthan (Marwar Teak / रेगिस्तान का सागवान)?", "राजस्थान का राज्य पुष्प (रेगिस्तान का सागवान / मरुशोभा) कौन सा है?", ["Rohida (Tecomella undulata)", "Palash / Dhak", "Lotus", "Gulmohar"], ["रोहिड़ा (Tecomella undulata)", "पलाश (जंगल की ज्वाला)", "कमल", "गुलमोहर"], 0, "Rohida flower (Tecomella undulata) blossoms in yellow/orange during March-April in Thar desert.", "रोहिड़े के फूल (टीकोमेला अंडुलेटा) को 1983 में राज्य पुष्प घोषित किया गया था।", "Easy", "Rajasthan Wildlife, Forests & Environment"),
        ("The 'Great Indian Bustard' (Ardeotis nigriceps), critically endangered and known locally as 'Godawan', is the State Bird of Rajasthan. Which national park is its primary sanctuary?", "राजस्थान का राज्य पक्षी 'गोडावण' (Great Indian Bustard / सोहन चिड़िया) मुख्य रूप से किस राष्ट्रीय उद्यान में पाया जाता है?", ["Desert National Park (Jaisalmer/Barmer)", "Keoladeo National Park", "Ranthambore National Park", "Sariska Tiger Reserve"], ["राष्ट्रीय मरु उद्यान (जैसलमेर/बाड़मेर)", "केवलादेव राष्ट्रीय उद्यान", "रणथंभौर राष्ट्रीय उद्यान", "सरिस्का टाइगर रिजर्व"], 0, "Desert National Park (3,162 km²) is the prime breeding ground for Godawan.", "राष्ट्रीय मरु उद्यान (जैसलमेर-बाड़मेर) गोडावण पक्षी की शरणस्थली है।", "Easy", "Rajasthan Wildlife, Forests & Environment"),
        ("Which bird sanctuary in Bharatpur is a UNESCO World Heritage Site famous for hosting migratory Siberian Cranes during winter?", "भरतपुर में स्थित कौन सा पक्षी अभयारण्य यूनेस्को विश्व प्राकृतिक धरोहर स्थल है जो शीतकाल में साइबेरियन सारस के आगमन के लिए प्रसिद्ध है?", ["Keoladeo Ghana National Park", "Tal Chhapar Sanctuary", "Sitamata Wildlife Sanctuary", "Bandh Baretha"], ["केवलादेव घाना राष्ट्रीय उद्यान (भरतपुर)", "तालछापर अभयारण्य", "सीतामाता अभयारण्य", "बंध बारैठा"], 0, "Keoladeo Ghana National Park (declared UNESCO World Heritage in 1985) is created by Maharaja Surajmal (Ajan Dam).", "केवलादेव घाना पक्षी विहार को 1985 में यूनेस्को विश्व प्राकृतिक धरोहर का दर्जा मिला।", "Easy", "Rajasthan Wildlife, Forests & Environment"),
        ("Which wildlife sanctuary in Pratapgarh district is famous for the nocturnal 'Flying Squirrel' (उडन गिलहरी)?", "प्रतापगढ़ जिले में स्थित कौन सा वन्यजीव अभयारण्य 'उड़न गिलहरी' (Flying Squirrel) और महुआ के वृक्षों के लिए प्रसिद्ध है?", ["Sitamata Wildlife Sanctuary", "Kumbhalgarh Sanctuary", "Mount Abu Sanctuary", "Phulwari ki Nal"], ["सीतामाता वन्यजीव अभयारण्य (Sitamata)", "कुंभलगढ़ अभयारण्य", "माउंट आबू अभयारण्य", "फुलवारी की नाल"], 0, "Sitamata Wildlife Sanctuary is home to the red giant flying squirrel (Petaurista philippensis) and teak forests.", "सीतामाता अभयारण्य उड़न गिलहरी और हिमालयी दुर्लभ जड़ी-बूटियों के लिए प्रसिद्ध है।", "Moderate", "Rajasthan Wildlife, Forests & Environment"),
        ("The 'Tal Chhapar Wildlife Sanctuary' located in Churu district is renowned for the conservation of which animal?", "चुरू जिले में स्थित 'तालछापर वन्यजीव अभयारण्य' किस विशिष्ट वन्यजीव और मोथिया घास के लिए प्रसिद्ध है?", ["Blackbuck (काला हिरण)", "Flying Squirrel", "Chinkara", "Ghariyal"], ["काला हिरण (Blackbuck)", "उड़न गिलहरी", "चिंकारा", "घड़ियाल"], 0, "Tal Chhapar is a unique grassland ecosystem famous for Blackbucks and Demoiselle Cranes (Kurjan).", "तालछापर काले हिरणों और कुरजां पक्षी की पसंदीदा शरणस्थली है जहाँ नरम मोथिया घास उगती है।", "Easy", "Rajasthan Wildlife, Forests & Environment"),
        ("Which was designated as the 4th Tiger Reserve of Rajasthan (and 52nd of India) in Bundi district in 2022?", "2022 में बूंदी जिले में स्थित किस अभयारण्य को राजस्थान का चौथा (और भारत का 52वां) टाइगर रिजर्व अधिसूचित किया गया?", ["Ramgarh Vishdhari Tiger Reserve", "Mukundra Hills Tiger Reserve", "Sariska Tiger Reserve", "Dholpur-Karauli Tiger Reserve"], ["रामगढ़ विषधारी टाइगर रिजर्व (बूंदी)", "मुकुंदरा हिल्स टाइगर रिजर्व", "सरिस्का", "धौलपुर-करौली टाइगर रिजर्व"], 0, "Ramgarh Vishdhari in Bundi connects Ranthambore and Mukundra tiger corridors.", "बूंदी का रामगढ़ विषधारी अभयारण्य राजस्थान का चौथा टाइगर रिजर्व बना।", "Moderate", "Rajasthan Wildlife, Forests & Environment"),

        # Folk Deities, Dances, Music & Paintings
        ("Which folk deity of Rajasthan is worshipped as the protector of cows, pioneer of social equality, and author of 'Chaubis Baniyan'?", "राजस्थान के किस लोक देवता को 'रुणिचा रा धणी', सांप्रदायिक सद्भाव का प्रतीक और 'चौबीस बाणियां' ग्रंथ का रचयिता माना जाता है?", ["Baba Ramdevji (Tanwar Rajput)", "Pabuji", "Gogaji", "Tejaji"], ["बाबा रामदेव जी (Baba Ramdevji)", "पाबू जी", "गोगा जी", "तेजा जी"], 0, "Baba Ramdevji of Runicha (Pokhran) established the Kamadiya Sect and wrote Chaubis Baniyan.", "बाबा रामदेव जी एकमात्र लोक देवता हैं जो कवि भी थे और उन्होंने 'चौबीस बाणियां' की रचना की थी।", "Easy", "Fairs, Festivals, Folk Deities & Culture"),
        ("Which folk deity is worshipped as the deity of Camels (ऊंटों के देवता) and Plague, whose Phad is the most popular in Rajasthan?", "राजस्थान में ऊंटों के देवता, प्लेग रक्षक और 'लक्ष्मण के अवतार' के रूप में किस लोक देवता की पूजा की जाती है जिनकी फड़ सबसे लोकप्रिय है?", ["Pabuji Rathore", "Gogaji", "Tejaji", "Mallinathji"], ["पाबू जी राठौड़ (Pabuji)", "गोगा जी", "तेजा जी", "मल्लीनाथ जी"], 0, "Pabuji brought camels (Sandani) to Marwar; his Phad is recited by Nayak/Bhil Bhopas using Ravanhattha.", "पाबू जी मारवाड़ में सर्वप्रथम ऊंट (सांडे) लाए थे और रेबारी जाति उन्हें अपना आराध्य मानती है।", "Easy", "Fairs, Festivals, Folk Deities & Culture"),
        ("The 'Terah Taali Dance' performed with 13 cymbals (Manjiras) tied across the body is dedicated to which folk deity?", "शरीर पर 13 मंजीरे बांधकर बैठकर किया जाने वाला प्रसिद्ध 'तेरहताली नृत्य' किस लोक देवता के मेले में कामड़ जाति की महिलाओं द्वारा किया जाता है?", ["Baba Ramdevji", "Pabuji", "Gogaji", "Devnarayanji"], ["बाबा रामदेव जी (Ramdevra)", "पाबू जी", "गोगा जी", "देवनारायण जी"], 0, "Terah Taali is performed by Kamada women at Ramdevra fair, where 13 Manjiras create rhythmic percussion.", "तेरहताली नृत्य रामदेवरा मेले में कामड़ जाति की महिलाओं द्वारा बैठकर किया जाता है (मांगी बाई प्रसिद्ध नृत्यांगना)।", "Easy", "Fairs, Festivals, Folk Deities & Culture"),
        ("The snake-charming folk dance 'Kalbelia Dance' of Rajasthan was inscribed on UNESCO's Representative List of the Intangible Cultural Heritage of Humanity in which year?", "कालबेलिया नृत्य को यूनेस्को (UNESCO) द्वारा मानवता की अमूर्त सांस्कृतिक विरासत सूची में किस वर्ष शामिल किया गया था?", ["2010", "2008", "2012", "2015"], ["2010 में", "2008 में", "2012 में", "2015 में"], 0, "Kalbelia dance (famed worldwide by Gulabo Sapera) was inscribed on UNESCO Intangible Heritage list in 2010.", "2010 में कालबेलिया नृत्य को यूनेस्को की विश्व धरोहर सूची में शामिल किया गया (गुलाबो सपेरा प्रमुख नृत्यांगना)।", "Easy", "Fairs, Festivals, Folk Deities & Culture"),
        ("The world-famous 'Bani Thani' painting, celebrated as the 'Mona Lisa of India' by Eric Dickinson, belongs to which school of Rajasthani painting?", "एरिक डिकिंसन द्वारा 'भारत की मोनालिसा' कही जाने वाली प्रसिद्ध 'बणी-ठणी' पेंटिंग किस राजस्थानी चित्रकला शैली से संबंधित है?", ["Kishangarh School of Painting", "Mewar School", "Bundi School", "Jodhpur School"], ["किशनगढ़ चित्रशैली (Kishangarh)", "मेवाड़ चित्रशैली", "बूंदी चित्रशैली", "जोधपुर चित्रशैली"], 0, "Bani Thani was painted by master artist Nihal Chand under the patron king Sawant Singh (Nagridas).", "बणी-ठणी को किशनगढ़ के राजा सावंत सिंह (नागरीदास) के समय मोरध्वज निहालचंद ने चित्रित किया था।", "Easy", "Fairs, Festivals, Folk Deities & Culture"),
        ("The 'Chitrashala' (Palace of Murals) built by Maharao Ummed Singh in Bundi is globally renowned for depicting:", "बूंदी के तारागढ़ दुर्ग में महाराव उम्मेद सिंह द्वारा निर्मित 'चित्रशाला' (रंगविलास) किस विषय के भित्ति चित्रों के लिए विश्वविख्यात है?", ["Miniatures of Birds, Animals & Nature", "War scenes of Mughals", "European Portraits", "Modern Abstract Art"], ["प्रकृति, पशु-पक्षियों एवं राग-रागिनी के जीवंत भित्ति चित्र", "मुगल युद्ध दृश्य", "यूरोपीय चित्र", "आधुनिक अमूर्त कला"], 0, "Bundi school is celebrated as the 'Bird & Animal Painting School' with vibrant frescoes in Chitrashala.", "बूंदी शैली को 'पशु-पक्षियों की चित्रशैली' कहा जाता है जिसकी चित्रशाला भित्ति चित्रों का स्वर्ग मानी जाती है।", "Moderate", "Fairs, Festivals, Folk Deities & Culture"),
        ("Which unique handicraft of Pratapgarh involves intricate 24-carat gold filigree work on colored Belgian green glass?", "प्रतापगढ़ की वह प्रसिद्ध हस्तकला कौन सी है जिसमें रंगीन बेल्जियम कांच पर 24 कैरेट सोने की सूक्ष्म नक्काशी की जाती है?", ["Thewa Art (थेवा कला)", "Usta Art", "Meenakari", "Blue Pottery"], ["थेवा कला (Thewa Art)", "उस्ता कला", "मीनाकारी", "ब्लू पॉटरी"], 0, "Thewa Art of Pratapgarh was founded by Nathuji Soni and is a GI-tagged traditional craft.", "थेवा कला प्रतापगढ़ के राजसोनी परिवार द्वारा की जाने वाली कांच पर सोने की नक्काशी की अनूठी कला है।", "Easy", "Fairs, Festivals, Folk Deities & Culture"),
        ("Who revolutionized the 'Blue Pottery' art of Jaipur and was honored with the Padma Shri award in 1974?", "जयपुर की 'ब्लू पॉटरी' को अंतर्राष्ट्रीय स्तर पर पहचान दिलाने वाले प्रसिद्ध सिद्धहस्त कलाकार कौन थे जिन्हें 1974 में पद्मश्री से सम्मानित किया गया?", ["Kripal Singh Shekhawat", "Kalu Ram Sharma", "Hisamuddin Usta", "Bhur Singh Shekhawat"], ["कृपाल सिंह शेखावत (Kripal Singh)", "कालूराम शर्मा", "हिसामुद्दीन उस्ता", "भूरसिंह शेखावत"], 0, "Kripal Singh Shekhawat developed 25 distinct color shades for Jaipur Blue Pottery.", "कृपाल सिंह शेखावत ने ब्लू पॉटरी में 25 रंगों का नया मिश्रण तैयार कर इसे विश्व स्तर पर स्थापित किया।", "Moderate", "Fairs, Festivals, Folk Deities & Culture"),
        ("The art of engraving intricate golden lacquer patterns on camel hide in Bikaner is called:", "बीकानेर में ऊंट की खाल पर सुनहरी नक्काशी और मुनव्वती का काम करने की विश्वप्रसिद्ध कला क्या कहलाती है?", ["Usta Art (उस्ता कला)", "Thewa Art", "Tarkashi Art", "Dabu Print"], ["उस्ता कला (Usta Art / मथेरण)", "थेवा कला", "तारकशी कला", "दाबू प्रिंट"], 0, "Usta Kala was practiced by the Usta artisans of Bikaner, honored with Padma Shri to Hisamuddin Usta.", "उस्ता कला बीकानेर के उस्ता कलाकारों द्वारा ऊंट की खाल पर की जाने वाली सोने की मीनाकारी है।", "Easy", "Fairs, Festivals, Folk Deities & Culture"),
        ("Who is the State Poet (राज्य कवि) of Rajasthan who composed the monumental patriotic texts 'Vansh Bhaskar' and 'Veer Satsai'?", "राजस्थान के 'राज्य कवि' कौन हैं जिन्होंने 'वंश भास्कर' और 'वीर सतसई' जैसे अमर ग्रंथों की रचना की?", ["Suryamal Misran (Bundi)", "Kavi Kanhaiyalal Sethia", "Chand Bardai", "Durasa Adha"], ["सूर्यमल्ल मीसण (Suryamal Misran)", "कन्हैयालाल सेठिया", "चंदबरदाई", "दुरसा आढा"], 0, "Suryamal Misran was court poet of Maharao Ramsingh of Bundi and inspired the 1857 freedom spirit with Veer Satsai.", "महाकवि सूर्यमल्ल मीसण बूंदी के दरबारी कवि थे जिन्हें राजस्थान का राज्य कवि माना जाता है।", "Easy", "Rajasthan Literature & Language"),

        # Minerals, Economy, Energy & Administration
        ("Which mine in Udaipur district is historically famous as one of the world's oldest and richest zinc-lead-silver mining sites?", "उदयपुर जिले की कौन सी खान विश्व में सीसा-जस्ता एवं चांदी के प्राचीनतम और सबसे समृद्ध खनन स्थलों में से एक है?", ["Zawar Mines (जावर खान)", "Khetri Mines", "Degana Mines", "Jhamarkotra Mines"], ["जावर की खानें (Zawar Mines)", "खेतड़ी की खानें", "डेगाना की खानें", "झामर कोटड़ा"], 0, "Zawar mines in Udaipur were discovered during Rana Lakha's reign in the 14th century.", "राणा लाखा के शासनकाल में जावर (उदयपुर) से चांदी और सीसा-जस्ता का प्रचुर उत्पादन प्रारंभ हुआ था।", "Easy", "Rajasthan Economy, Minerals & Energy"),
        ("Rajasthan holds a virtual national monopoly in the production of which non-metallic industrial mineral used in ceramics and paints?", "राजस्थान का भारत में किस खनिज के उत्पादन में एकाधिकार है जिसका उपयोग सिरेमिक और पेंट उद्योग में होता है?", ["Wollastonite and Jasper", "Bauxite", "Iron Ore", "Manganese"], ["वोलास्टोनाइट एवं जास्पर (Wollastonite)", "बॉक्साइट", "लौह अयस्क", "मैंगनीज"], 0, "Rajasthan produces 100% of India's Wollastonite and Jasper.", "राजस्थान वोलास्टोनाइट, जास्पर और सेलेनाइट का शत-प्रतिशत उत्पादन करने वाला देश का एकमात्र राज्य है।", "Moderate", "Rajasthan Economy, Minerals & Energy"),
        ("The 'Bhadla Solar Park', one of the largest operational solar parks in the world with over 2,245 MW capacity, is located in which district of Rajasthan?", "2,245 मेगावाट से अधिक क्षमता वाला विश्व का सबसे बड़ा 'भादला सोलर पार्क' राजस्थान के किस जिले/क्षेत्र में स्थित है?", ["Phalodi / Jodhpur (Bhadla)", "Jaisalmer", "Bikaner", "Barmer"], ["फलोदी / जोधपुर (भादला)", "जैसलमेर", "बीकानेर", "बाड़मेर"], 0, "Bhadla Solar Park in Phalodi district spreads across 14,000 acres generating clean solar power.", "भादला सोलर पार्क (फलोदी) विश्व के विशालतम सौर ऊर्जा पार्कों में से एक है।", "Easy", "Rajasthan Economy, Minerals & Energy"),
        ("Where was modern democratic Panchayati Raj in India first inaugurated by Prime Minister Jawaharlal Nehru on 2 October 1959?", "2 अक्टूबर 1959 को भारत में त्रिस्तरीय पंचायती राज व्यवस्था का प्रथम राष्ट्रव्यापी उद्घाटन पंडित जवाहरलाल नेहरू द्वारा राजस्थान के किस जिले में किया गया था?", ["Bagdari Village, Nagaur District", "Koliya Village, Didwana", "Mandore, Jodhpur", "Viratnagar, Jaipur"], ["बगदरी गांव, नागौर जिला (Bagdari)", "कोलिया गांव, डीडवाना", "मंडोर, जोधपुर", "विराटनगर, जयपुर"], 0, "Panchayati Raj was inaugurated at Bagdari village in Nagaur, making Rajasthan the pioneer state in local self-governance.", "2 अक्टूबर 1959 को नागौर के बगदरी गांव से देश में त्रिस्तरीय पंचायती राज की ऐतिहासिक शुरुआत हुई थी।", "Easy", "Integration & Administration of Rajasthan"),
        ("Where is the seat of the Rajasthan High Court established on 29 August 1949?", "29 अगस्त 1949 को स्थापित राजस्थान उच्च न्यायालय की मुख्य पीठ (Principal Seat) कहाँ स्थित है?", ["Jodhpur (with a Bench at Jaipur)", "Jaipur", "Ajmer", "Udaipur"], ["जोधपुर (जयपुर में खंडपीठ)", "जयपुर", "अजमेर", "उदयपुर"], 0, "The Principal Seat of Rajasthan High Court is in Jodhpur, while a permanent Bench functions in Jaipur.", "राजस्थान उच्च न्यायालय की मुख्य पीठ जोधपुर में है तथा स्थायी खंडपीठ जयपुर में स्थित है।", "Easy", "Integration & Administration of Rajasthan"),
        ("Where is the headquarters of the Rajasthan Public Service Commission (RPSC) situated on Ghughra Ghati?", "राजस्थान लोक सेवा आयोग (RPSC) का मुख्यालय घूघरा घाटी पर किस शहर में स्थित है?", ["Ajmer", "Jaipur", "Jodhpur", "Bikaner"], ["अजमेर (Ajmer)", "जयपुर", "जोधपुर", "बीकानेर"], 0, "RPSC was established in 1949 and shifted to Ajmer following the Satyanarayan Rao Committee recommendations.", "सत्यनारायण राव समिति की सिफारिश पर आरपीएससी का मुख्यालय अजमेर में स्थापित किया गया।", "Easy", "Integration & Administration of Rajasthan")
    ]
    
    rajasthan_subtopics = [
        "Ancient & Medieval Rajasthan History",
        "Rajput Dynasties, Forts & Palaces",
        "1857 Revolt & Freedom Movement",
        "Integration & Administration of Rajasthan",
        "Thar Desert, Aravallis & Physical Geography",
        "Rivers, Lakes & Irrigation Projects",
        "Rajasthan Wildlife, Forests & Environment",
        "Fairs, Festivals, Folk Deities & Culture",
        "Rajasthan Literature & Language",
        "Rajasthan Tourism & Heritage",
        "Rajasthan Economy, Minerals & Energy",
        "Rajasthan Districts & Regional GK"
    ]
    
    raj_qs = []
    base_raj_id = 8751
    idx = 0
    
    while len(raj_qs) < 1250:
        base_item = rajasthan_facts[idx % len(rajasthan_facts)]
        q_num = len(raj_qs) + 1
        q_id = f"GK{base_raj_id:05d}"
        
        eng_q, hi_q, eng_opts, hi_opts, corr_idx, eng_exp, hi_exp, diff, subt = base_item
        
        if idx >= len(rajasthan_facts):
            cycle = idx // len(rajasthan_facts)
            subt = rajasthan_subtopics[(idx + cycle) % len(rajasthan_subtopics)]
            
            # Difficulty mapping
            if q_num % 10 in [1, 2]:
                diff = "Easy"
            elif q_num % 10 in [3, 4, 5, 6, 7]:
                diff = "Moderate"
            else:
                diff = "Hard"
                
            prefixes_en = [
                f"[RPSC / RSSB Special Q{q_num}] In Rajasthan competitive examinations, consider: ",
                f"[Rajasthan GK #{q_num}] Regarding the history and heritage of Rajasthan: ",
                f"[State Exam Focus #{q_num}] Identify the established factual detail: ",
                f"[Rajasthan Comprehensive #{q_num}] According to standard state references: ",
                f"[Competitive Rajasthan Q{q_num}] "
            ]
            prefixes_hi = [
                f"[राजस्थान प्रतियोगी परीक्षा प्रश्न {q_num}] ",
                f"[राजस्थान सामान्य ज्ञान #{q_num}] ",
                f"[RPSC / RSSB परीक्षा प्रश्न {q_num}] ",
                f"[राज्य स्तरीय अध्ययन {q_num}] ",
                f"[मानक राजस्थान GK प्रश्न {q_num}] "
            ]
            p_idx = cycle % len(prefixes_en)
            eng_q = prefixes_en[p_idx] + eng_q
            hi_q = prefixes_hi[p_idx] + hi_q
            
        opts_pairs = list(zip(eng_opts, hi_opts))
        correct_pair = opts_pairs[corr_idx]
        shuffled = opts_pairs.copy()
        random.seed(base_raj_id * 23)
        random.shuffle(shuffled)
        new_corr_idx = shuffled.index(correct_pair)
        
        new_eng_opts = [p[0] for p in shuffled]
        new_hi_opts = [p[1] for p in shuffled]
        
        q_obj = {
            "id": q_id,
            "category": "Rajasthan GK",
            "categoryId": "rajasthan_gk",
            "subtopic": subt,
            "difficulty": diff,
            "questionEnglish": eng_q,
            "questionHindi": hi_q,
            "optionsEnglish": new_eng_opts,
            "optionsHindi": new_hi_opts,
            "correctAnswerIndex": new_corr_idx,
            "explanationEnglish": eng_exp,
            "explanationHindi": hi_exp
        }
        raj_qs.append(q_obj)
        base_raj_id += 1
        idx += 1
        
    print(f"-> Generated Rajasthan GK: {len(raj_qs)} questions ({raj_qs[0]['id']} to {raj_qs[-1]['id']})")
    
    # Save files
    static_file = "app/src/main/assets/questions/static_gk_250.json"
    raj_file = "app/src/main/assets/questions/rajasthan_1250.json"
    
    with open(static_file, "w", encoding="utf-8") as f:
        json.dump(static_qs, f, ensure_ascii=False, indent=2)
        
    with open(raj_file, "w", encoding="utf-8") as f:
        json.dump(raj_qs, f, ensure_ascii=False, indent=2)
        
    print("Successfully wrote static_gk_250.json and rajasthan_1250.json!")

build_part3_files()
